### ISSUE TITLE
Integration of Foreman and the inclusion of a Procfile for dev. environments

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/tiger-data-app#1039]
Currently, the Vite asset pipeline does not support the [Hot Module Replacement](https://vitejs.dev/guide/features.html#hot-module-replacement) when only `rails server` is invoked within the local development environment. In order to ensure that HMR is enabled and that modifications made to the SCSS files are dynamically updated in one's web browser, one must open a separate, new terminal and invoke `bundle exec ./bin/vite dev`. One alternative to this might be to please include https://github.com/ddollar/foreman as a dependency. Using a `Procfile` structured as the following:

```yaml
vite: bin/vite dev
web: bin/rails s
```

...one can then simply invoke `bundle exec foreman start`.

Please see https://github.com/pulibrary/orcid_princeton/issues/199 for reference

**Comment by kelynch** [comment]
Let's discuss this as a team before scheduling into a sprint.

**Comment by jrgriffiniii** [comment]
Following the discussion during the check-in meeting for this morning, it was determined that the preferred approach for this is to please invoke `rake assets:clobber` should issues arise with SCSS or JavaScript assets not being updated within the development environment
