### ISSUE TITLE
Remove "edit" buttons

### ISSUE THREAD

**Issue by kelynch** [pulibrary/tiger-data-app#1114]
Remove edit buttons from the interface for data managers and sponsors.  Leave them visible for admins like Chuck.

![Screenshot 2024-12-11 at 11 17 37 AM](https://github.com/user-attachments/assets/8d6ceda6-4d78-49dd-b6c5-39f274d99409)

There is already code checking what your role is to display these buttons.

## Acceptance criteria

- [ ] The edit buttons display only for sysadmins and superusers
- [ ] The edit buttons do not display for any users except sysadmins and superusers
- [ ] There is a test for this

**Comment by kelynch** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tigerdata-app/1114?planning-poker) with Zenhub @bess @carolyncole @hectorcorrea @JaymeeH @jrgriffiniii @leefaisonr

**Comment by bess** [comment]
Also posted on #tiger-data slack:
@matthewjchandler 
Sorry I didn’t notice during ticket refinement, but this ticket is unclear. Who should have the edit button? It says “Admins” but we dont’ have a thing called “Admins”. We have “sysadmins” and “superusers”:
```  
    user.eligible_sponsor = line["eligible_sponsor"] == "TRUE"
      user.eligible_manager = line["eligible_manager"] == "TRUE"
      user.superuser = line["superuser"] == "TRUE"
      user.sysadmin = line["sysadmin"] == "TRUE"
      user.trainer = line["tester_trainer"] == "TRUE"
```
That’s the language we’re using for roles right now

So who gets edit buttons?
a) sysadmins
b) superusers
c) both

Thanks!
