### ISSUE TITLE
Revisit demo MediaFlux code, post-retreat

### ISSUE THREAD

**Issue by kelynch** [pulibrary/tiger-data-app#116]
After the RDSS retreat day (March 13, 2023), revisit [this code](https://github.com/pulibrary/tiger-data-app/pull/114), [this code](https://github.com/pulibrary/tiger-data-app/pull/119), [this code](https://github.com/pulibrary/tiger-data-app/pull/120), and [this code](https://github.com/pulibrary/tiger-data-app/pull/118), and either remove or refactor it to pass CI/work with our agreed-upon programmatic approach sustainably.

Acceptance criteria:
- [ ] Add pagination to classes https://github.com/pulibrary/tiger-data-app/tree/main/app/models/mediaflux
- [ ] Add additional classes to https://github.com/pulibrary/tiger-data-app/tree/main/app/models/mediaflux
- [ ] Edit the code and update to utilize helper classes in https://github.com/pulibrary/tiger-data-app/tree/main/app/models/mediaflux

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/116?planning-poker) with Zenhub @bess @jrgriffiniii
