### ISSUE TITLE
Document aterm scripts needed to get started with MediaFlux trainings

### ISSUE THREAD

**Issue by kelynch** [pulibrary/tiger-data-app#136]
Builds on #128 

completion criteria:

- [x] Create a document in the doc/ directory to house the information
- [x] Document the Create operation in Aterm with examples
- [x] Document the Read operation in Aterm with examples
- [x] Document the Update operation in Aterm with examples
- [x] Document the Delete operation in Aterm with examples

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/136?planning-poker) with Zenhub @bess @hectorcorrea @jrgriffiniii
