### ISSUE TITLE
Complete MediaFlux 201 training

### ISSUE THREAD

**Issue by bess** [pulibrary/tiger-data-app#139]
Go through the MediaFlux 201 training and ask team for support as needed.
Recordings here: https://drive.google.com/drive/folders/1qozikkir5KheEMZX_Lyo-BBLQxUxj7Zk

- [ ] Bess
- [ ] Kate

**Comment by kelynch** [comment]
Moving out of sprint until MF301 training is confirmed and API-focused format is finalized.
