### ISSUE TITLE
Create Tickets for the epic Preliminary Project Creation Form

### ISSUE THREAD

**Issue by kelynch** [pulibrary/tiger-data-app#151]
Compare https://github.com/pulibrary/tiger-data-app/issues/113 with current software and identify gaps.

Acceptance criteria:

- [x] Schedule a meeting to do the comparison to include Matt (at least 1 hour)
- [x] After the meeting there will be tickets created that are actionable (small and specific)

**Comment by hectorcorrea** [comment]
Tickets
* https://github.com/pulibrary/tiger-data-app/issues/169
* https://github.com/pulibrary/tiger-data-app/issues/170
* https://github.com/pulibrary/tiger-data-app/issues/171
* https://github.com/pulibrary/tiger-data-app/issues/172
