### ISSUE TITLE
create_collection_asset does not seem to be working

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/tiger-data-app#154]
MediaFluxClient#create_collection_asset is not generating the expected result.

The collection is being created, aka you can see it in the desktop, but the project is not getting displayed and there are a number of errors in the log `asset.namespace.describe' failed: The namespace '/td-demo-001/rc/test-2-ns/test-2' does not exist or is not accessible` 

This may be because it is a collection and not a namespace?

**Comment by hectorcorrea** [comment]
More information about this: https://docs.google.com/document/d/1G8yjEGOdiTtwrScgR8jwNQ7Cvl9BIR53OLPrEO5MrtY/edit#heading=h.q6jrx6d9muf9

**Comment by hectorcorrea** [comment]
This has been fixed.
