### ISSUE TITLE
Integrate accessibility audits into automated builds

### ISSUE THREAD

**Issue by kelynch** [pulibrary/tiger-data-app#157]
Enable automated accessibility checking so we ensure that the UI we build works for a wide range of users.  We should do this the same way we did for PDC Discovery: https://github.com/pulibrary/pdc_discovery/pull/135

## Acceptance Criteria

- [ ] Our CI process automatically checks accessibility, via axe-core-rspec

**Comment by kelynch** [comment]
Another good example: https://github.com/pulibrary/pdc_describe/pull/44/files

**Comment by kelynch** [comment]
@JaymeeH It looks like this is fully addressed in #242, is that correct?  Can this issue be closed?

**Comment by JaymeeH** [comment]
correct, this issue can be closed
