### ISSUE TITLE
Project new and edit page

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/tiger-data-app#170]
Update the Project new and edit form to allow the user to enter the information indicated in the project schema (see https://github.com/pulibrary/tiger-data-app/issues/169) and enforce the required fields.

* For this version we can keep it simple and force the user to enter a project ID (rather than calculating this from an automatically generated DOI). 
* Title is required
* Description is required
* Data Sponsor (a netid) is required
* Data Manager (a netid) is required
* Departments is a multi-value field, at least one is required. For this version use a hard coded list of departments with code/name and store the codes in the record.
* Notice that the `data_users_rw` and `data_users_ro` are optional fields and we'll implement those in ticket https://github.com/pulibrary/tiger-data-app/issues/171

Acceptance Criteria:
- [x] Allow the user to enter the data in the form above and store into our tigerdata database
- ~~[ ] Matt gets an email with the information above~~ (moved to ticket #195)
- [x] No interaction with mediaflux 
- [x] No interaction with DataCite

**Comment by kelynch** [comment]
Clarification in meeting notes (and added to acceptance criteria above) - https://docs.google.com/document/d/14SjoKlTI7AWNVNjgBOa28jDnhClTnaMnEgN5EBocR9o/edit#heading=h.f44bvi1wdwt3

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/170?planning-poker) with Zenhub @kelynch @bess @jrgriffiniii

**Comment by hectorcorrea** [comment]
Move the email notification to its own ticket: https://github.com/pulibrary/tiger-data-app/issues/195

**Comment by hectorcorrea** [comment]
Reopening since I still need to update Mediaflux on updates.

**Comment by hectorcorrea** [comment]
https://github.com/pulibrary/tiger-data-app/pull/197 took care of it.
