### ISSUE TITLE
Project edit page - data users

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/tiger-data-app#171]
Implement the code to allow a user to add many read-write data users and many read-only data users. The value entered for a "data user" will be their `netid`. 

This should be a comma separated list for the moment.
 See [wireframes](https://github.com/pulibrary/tiger-data-app/issues/113)
Acceptance Criteria:

- [ ] There are two text boxes that allow the user to enter a comma separated list

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/171?planning-poker) with Zenhub @bess @jrgriffiniii @kelynch
