### ISSUE TITLE
Project show page

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/tiger-data-app#172]
Update the Show page to display the data captured in https://github.com/pulibrary/tiger-data-app/issues/170 and https://github.com/pulibrary/tiger-data-app/issues/171

See https://github.com/pulibrary/tiger-data-app/issues/113 for UI ideas

Acceptance Criteria:

- [ ] Be able to show the information stored in the database about a project
- [ ] It should not contact mediaflux, but may need to in the future

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/172?planning-poker) with Zenhub @bess @jrgriffiniii @kelynch
