### ISSUE TITLE
New access rights to tigerdata app account

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/tiger-data-app#176]
Figure out how to grant access to the account `princeton:tigerdata` to a few commands that we need but don't have access to. In particular we need access to `asset.doc.type.update` and `secure.identity.token.create` ([more info](https://docs.google.com/document/d/14OkV7zwMplyWv2VN-WUYtpTgRN4eSGIhPKQh14SFcD4/edit#heading=h.umr1qsxf0mbf))

In our local instance of MediaFlux the user `system:manager` user has access to execute these commands, but we should figure out the right commands to grant the new access to our user so Robert Knight can update the account in `td-meta1`

**Comment by carolyncole** [comment]
I think `princeton:tigerdata` needs to have the system:administrator role added because the documentation indicates to create tokens for other user you need to be an administrator.

**Comment by carolyncole** [comment]
I contacted Robert in slack.  He is going to add `asset.doc.namespace.update` and `asset.doc.type.update` to `princeton:tigerdataapp` on td-meta1

**Comment by carolyncole** [comment]
From what I can tell the accounts now have access to `asset.doc.namespace.update` and `asset.doc.type.update`. The code does not seem to be creating new namespaces, but I will create another ticket for that...
