### ISSUE TITLE
Mediaflux like it best (faster) when http connections are kept open over multiple API calls

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/tiger-data-app#180]
Currently we code our http connection every time we make a request to Mediaflux.

It would be good it we could keep the http connection to mediaflux open for the duration of the controller, or longer.

Open Call: https://github.com/pulibrary/tiger-data-app/blob/main/app/models/mediaflux/http/request.rb#L59
Close call: https://github.com/pulibrary/tiger-data-app/blob/main/app/models/mediaflux/http/request.rb#L71

In theory we could pass in an http object to the request and note that it is not ours so the we would not shut it down

At the moment we assume the http object is ours and shut it down every time.

**Comment by kelynch** [comment]
This should be revisited after we sort out authentication.

**Comment by jrgriffiniii** [comment]
Carolyn also found that the Docker container was dying when excessive connections were being created and destroyed for `aterm`. Perhaps there is a database connection pool pattern which must be implemented?

**Comment by kelynch** [comment]
This [Python client](https://gitlab.unimelb.edu.au/resplat-mediaflux/python-mfclient) indicates that users need to implement their own connection pool for concurrent tasks.

**Comment by jrgriffiniii** [comment]
This is not completely resolved, as the `finalizer` implemented in https://github.com/pulibrary/tiger-data-app/pull/517 is not called as consistently as I was hoping that it might be. I also do not completely have a clear understanding of the acceptance criteria for this, and would like to please request assistance and review with understanding what remains to be addressed for this.

**Comment by jrgriffiniii** [comment]
As discussed during the check-in meeting on 02/26/24, the `finalizer` at the Object-level is actually introducing a performance decrease. This must be removed, and then this issue can be closed.
