### ISSUE TITLE
Upgrade tigerdata staging and prod to postgres 15

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/tiger-data-app#186]
tigerdata-staging and tigerdata-prod are pointing at the postgres 13 staging database.  We should be pointing at the new posgres 15 database I think...

This should be self-documenting in princeton_ansible.

## Acceptance criteria
- [x] Check whether this happened already
- [ ] If it didn't re-write this ticket

**Comment by bess** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/186?planning-poker) with Zenhub @carolyncole @hectorcorrea @JaymeeH @jrgriffiniii @leefaisonr

**Comment by Seanwarren77** [comment]
This already happened, you can see it in ansible here: https://github.com/pulibrary/princeton_ansible/blob/main/group_vars/tigerdata/common.yml#L3
