### ISSUE TITLE
Limit who can login and create projects

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/tiger-data-app#200]
Before we can let users utilize the system we need a way to limit who can login and create projects.  This is part of #112 

I think the simplest way to do this is just to create a configuration file with a list of users who are allowed to sponsor projects, but really anything that keeps people who are not in Matt's list of early adopters from playing with the system will do.

- [x] Create a way to mark a user as a Data Sponsor
- [x] Check the user role before showing them the new project dashboard
- [x] Create a help page for users who are not on the list #112 has the text for this page

**Comment by matthewjchandler** [comment]
We have a new email for TigerData services, so we'll need to update the help text to match. I'm suggesting this line: "If you have any questions, please contact the team at [tigerdata@princeton.edu](mailto:tigerdata@princeton.edu)."
