### ISSUE TITLE
What URL path will this run at?

### ISSUE THREAD

**Issue by bess** [pulibrary/tiger-data-app#223]
- [ ] Do we need to add a /tigerdata (or something else?) path
- [ ] Do we need to take over the domain name tigerdata.princeton.edu on our load balancer and point it at another location for the top domain and to our application for the directory name?

**Comment by kelynch** [comment]
After conversing with Operations, it looks like the best course of action would be not to host this application under a subdirectory of the tigerdata.princeton.edu domain.  I'll work with Matt to come up with a URL path we should use.

**Comment by bess** [comment]
Thank you!
