### ISSUE TITLE
Performance test for collection queries

### ISSUE THREAD

**Issue by kelynch** [pulibrary/tiger-data-app#224]
From [Feature Refinement notes](https://docs.google.com/document/d/14SjoKlTI7AWNVNjgBOa28jDnhClTnaMnEgN5EBocR9o/edit#heading=h.f1qpx09g69fj):

Run an experiment on a group of collections as follows:

Run both of these queries separately: 
* Query by data sponsor and collect time
* Query by department and collect time

On the same group of collection in the following three settings:
* All collection under 1 namespace
* All collection under a distributed namespace
* All collections under their own namespace

**Comment by hectorcorrea** [comment]
Creating 1000 projects in staging under the same namespace (e.g. `td-demo-001/project1...1000`) works rather well. Creating the projects took less than 2 minutes and queries come back within a few milliseconds

```
# 1,000 projects in staging

Creating 1000 projects with prefix oct26b...
Creating projects 16397.64 ms 163.98 seconds (~2 minutes)

Getting counts by data_sponsor zz001 16.13 ms 0.16 seconds
Getting counts by data_sponsor zz003 35.74 ms 0.36 seconds
Getting counts by data_sponsor zz007 66.79 ms 0.67 seconds
Getting counts by data_sponsor  10.60 ms 0.11 seconds

{:data_sponsor=>"zz001", :count=>"578"}
{:data_sponsor=>"zz003", :count=>"289"}
{:data_sponsor=>"zz007", :count=>"143"}
{:data_sponsor=>"total", :count=>"1015"}

Getting counts by data_sponsor zz007 department THREE 17.24 ms 0.17 seconds
47 records for data_sponsor zz007 department THREE
```

*Creating 10,000 projects under the same namespace on the other hand showed some problems*. It took about 30 minutes to create them (which is no big deal since we won't be creating 10,000 projects at once often) but the larger issue was that queries then started to take 1 to 2 seconds (rather than milliseconds).

```
# 10,000 projects in staging
Creating 10000 projects with prefix oct26c...
Creating projects 186119.23 ms 1861.19 seconds (~30 minutes)

Getting counts by data_sponsor zz001 235.55 ms 2.36 seconds
Getting counts by data_sponsor zz003 235.05 ms 2.35 seconds
Getting counts by data_sponsor zz007 231.55 ms 2.32 seconds
Getting counts by data_sponsor  118.83 ms 1.19 seconds

{:data_sponsor=>"zz001", :count=>"6293"}
{:data_sponsor=>"zz003", :count=>"3146"}
{:data_sponsor=>"zz007", :count=>"1571"}
{:data_sponsor=>"total", :count=>"11015"}
Getting counts by data_sponsor zz007 department THREE 230.85 ms 2.31 seconds
523 records for data_sponsor zz007 department THREE
```

**Comment by hectorcorrea** [comment]
Final benchmark document: https://docs.google.com/document/d/1alI7Sua8CbOH5Nuj7WhVf6x6yu--NXJ8eaxSWqYs7ms/edit
