### ISSUE TITLE
Watch MediaFlux Training 

### ISSUE THREAD

**Issue by leefaisonr** [pulibrary/tiger-data-app#244]
Videos locations link: https://drive.google.com/drive/folders/1UqQlsx91hVlc2YFIVmnBHLfO8iiMIP6U
- [ ] The videos are viewed as a group of at least two
- [x] Session 1 part 1 (schedule a meeting)
- [x] Session 1 part 2
- [ ] Session 2
- [ ] Session 3 
- [ ] Session 4 

The notes that we captured while we attended the training are here:
* [Training notes](https://drive.google.com/drive/folders/1kG6oJBnGqOUdM2cHKPxCOC9fBmAJ7iDo)
* [Hector's training notes](https://drive.google.com/drive/folders/1HGPp43OcGikdZmr3Wd4tgdpY6m1y_PCx)
* [Recordings for 101 and 201 sessions](https://drive.google.com/drive/folders/19EGm7s7UxOMCCdRRXSscUIkya_gF9Zgs)

**Comment by bess** [comment]
We discussed and agreed that session 1 was useful, but the other ones not so much. Taking out of sprint until someone decides otherwise.
