### ISSUE TITLE
Confirm access and privileges on TigerData staging server

### ISSUE THREAD

**Issue by kelynch** [pulibrary/tiger-data-app#25]
All members of the RDSS team should SSH into the new TigerData staging server and confirm access, as well as their ability to view appropriate logs (MediaFlux and system).

Connection details are in LastPass.

## Acceptance Criteria 

Each member of the team should: 
* SSH to the server using CAS/net ID
* Run "sudo -l" to see which commands are available for log analysis
* Cat/tail MediaFlux and system logs to confirm privileges 
* Separately, log onto the web-based desktop client with CAS/net ID (must be on VPN) and confirm access

Check your name off once you have done this.

- [x] Bess
- [x] James
- [x] Hector
- [x] Carolyn
- [x] Kate
- [x] Chuck

**Comment by jrgriffiniii** [comment]
Thank you for detailing these tasks, please know that I have successfully completed these steps.

**Comment by hectorcorrea** [comment]
All the `sudo -l` commands listed that point to `/home/MFLUX/volatile/...` worked for me and I suspect that's all we really need.

The few sudo -l commands that pointed to `/var/log/messages` and `/var/log/secure` DID NOT work for me.

**Comment by bess** [comment]
`sudo /usr/bin/cat /var/log/messages` and `sudo /usr/bin/cat /var/log/secure` worked for me.
So did everything else I tried.

**Comment by mccalluc** [comment]
These all work for me:
```
    sudo tail /var/log/messages
    sudo tail /var/log/secure
    sudo tail /home/MFLUX/volatile/logs/http.2.log
    sudo tail /home/MFLUX/volatile/logs/mediaflux-server.log
    sudo tail /home/MFLUX/volatile/logs/internal.1.log
    sudo tail /home/MFLUX/volatile/logs/syslog.log
```
