### ISSUE TITLE
Data Sponsor role field pre-filling

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/tiger-data-app#252]
### User Story
As a Data Sponsor, when I launch a new project request, I need my own NetID to be pre-filled and validated in the Data Sponsor field, so that I can avoid confusion and save time.

### Notes
Following up on #170, we need the preliminary form to auto-populate the NetID of the person who launched it: 

![image](https://github.com/pulibrary/tiger-data-app/assets/66128387/44068c8a-3cab-440e-854a-6608924471f5)

### Completion Criteria
- [x] The "Data Sponsor" field is required, singular, and takes a ~~valid~~ NetID as a value
- [x] The "Data Sponsor" field auto-populates the NetID of the person who launched the form
- [x] The "Data Sponsor" field is editable even after pre-population

**Update:** Note that this does NOT ensure that a netid is "valid". That is covered by other tickets, for various definitions of "valid"

**Comment by bess** [comment]
![Screenshot 2023-12-14 at 8 44 29 AM](https://github.com/pulibrary/tiger-data-app/assets/65608/3c7bcb75-7b8d-4334-b4e7-8494bedfe81e)
