### ISSUE TITLE
Validation for the "Project Directory" field on the new project request form

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/tiger-data-app#253]
### User Story
As a Data Sponsor, when I am filling out the "Project Directory" field on the new project request form, I need it to stop me immediately if I enter a value that could cause problems on some or all systems, so I don't have to go back and forth with the system administrators after submitting the form.

### Notes
Following up from #170, the project directory field needs to go a step further to validate entries to be file-path safe. We can adjust this in the future, but for now, my recommendation is to enforce Unicode, limit the entry to 64 characters total, and prohibit characters other than alphanumeric (case-sensitive), minus-dash, and underscore. If you have a suitable alternative to writing new code to do this explicitly, that's fine. We just need a way to nip problematic characters in the bud.

![image](https://github.com/pulibrary/tiger-data-app/assets/66128387/2546899b-e90d-44a6-9e55-f56b06fc0f53)

### Completion Criteria
- [x] The "Project Directory" field is required and singular
- [x] The "Project Directory" field only accepts a string of up to 64 Unicode alphanumeric, minus-dash, and/or underscore characters (or a suitable alternative method for ensuring that values are file path-safe on all systems)
- [ ] Current system of surfacing issues is fine, just augment it to add the character limitations
- [ ] Testing must account for the fact that some directories with be capitalized

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/253?planning-poker) with Zenhub @bess @hectorcorrea @JaymeeH @jrgriffiniii @kelynch @leefaisonr
