### ISSUE TITLE
Preliminary cancel button for the new project request form

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/tiger-data-app#255]
### User Story
As a Data Sponsor, after I have entered the new project request form, I need a way to explicitly cancel the request, so I can be assured that no actions will be taken if I decide not to proceed.

![TD_NewProjectForm_CancelButton_2023-12-05](https://github.com/pulibrary/tiger-data-app/assets/66128387/5488ab4b-49aa-4049-8016-5c2cf50d8c82)

### Notes
This depends on the framework being in place from #251. The idea is to have just two simple actions for the preliminary new project request form: submit and cancel. To cancel is to lose all entered data and go back to the dashboard. Draft DOIs should not be reserved until a valid form is submitted, so there should not be any external cleanup to worry about. And we won't worry about any "are you sure?" message for now.

### Completion Criteria
- [x] The "Cancel" button is clickable at any time after entering the new project request form
- [x] Clicking the "Cancel" button returns the user to the preliminary dashboard page, with no changes to the list of projects
- [x] Clicking the "Cancel" button does not save anything that was entered in the form

**Comment by sfazli96** [comment]
Hi! I am a little confused about what this issue is specifically or how it's happening in which file. Can you please explain a little more? If possible I can be assigned to this and I can give it a try to fix the issue. Thanks!

**Comment by kelynch** [comment]
We are not drafting/minting DOIs in this system at this time.
