### ISSUE TITLE
Project Details - pending status message

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/tiger-data-app#263]
If the project in question is still pending, then the "Project Details" page displays the following message immediately after the page title: "Your new project request is in the queue. Please allow 5 business days for our team to review your needs and set everything up. For assistance, please contact tigerdata@princeton.edu."

A project is still pending if it does not have a `mediaflux_id`

The form is in `app/views/projects/show.html.erb`

Acceptance Criteria 
- [ ] Pending message shows for pending projects
- [ ] Pending message does not show for approved projects

**Comment by hectorcorrea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/263?planning-poker) with Zenhub @JaymeeH @jrgriffiniii @leefaisonr
