### ISSUE TITLE
Project Details page - headings

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/tiger-data-app#264]
The "Project Details" page has 4 headings: "Roles", "Description", "Automatic Settings", and "Provenance"

These changes apply to the show and edit pages (`app/views/projects/show.html.erb` and `app/views/projects/_edit_form.html.erb`)

The only value that we have for "Automatic Settings" at this point is the `mediaflux id`. 

Display the `created_by/on` and `updated_by/on` under the Provenance section.

**Comment by hectorcorrea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/264?planning-poker) with Zenhub @JaymeeH @jrgriffiniii @leefaisonr

**Comment by JaymeeH** [comment]
Since provenance and automatic settings are static (unchangeable) fields, should we be adding them to the edit form? @matthewjchandler

**Comment by matthewjchandler** [comment]
@JaymeeH we will eventually have more fields available to enter/edit in forms, including some of those that are currently automatic settings. We will also eventually have a way to update provenance values via interoperation with other systems. But in this preliminary phase, the editable fields are limited, as shown in #113 and #248. All we need is for this issue is for the "Project Details" page to have a place to display "Automatic Settings" and "Provenance" values (which will be set for a given project by other means).

Right now, we just show roles and (project) description:
![image](https://github.com/pulibrary/tiger-data-app/assets/66128387/9498c9e0-e743-4c82-ad67-e0b7783265b6)

But what we need is a more complete overview of the project details, like this:
![image](https://github.com/pulibrary/tiger-data-app/assets/66128387/a40061f1-3f11-4bd5-8ef9-12ea8ac3141b)

And again, this issue is just about getting the headings cleaned up: "Roles", "Description", "Automatic Settings", and "Provenance"
