### ISSUE TITLE
Project Details page - names in role values

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/tiger-data-app#265]
### User Story
As a Data Sponsor, I need to be able to review the persons who are filling various roles on my project quickly and straightforwardly, so that I can fulfill my duty to oversee the project in the limited time I have available.

### Notes
We started by working only with NetIDs for roles, which are the proper way to enter role values for now (see #285). The problem is, NetIDs are often cryptic, and in the process of reviewing a sponsored project, it's critical that a Data Sponsor can see plainly who is assigned to what level of access.

![TD_ProjectDetails_RoleValues_2023-12-12](https://github.com/pulibrary/tiger-data-app/assets/66128387/618d2ddb-a33b-4dc3-8132-dabf80ba5772)

We have [a place in the metadata schema](https://docs.google.com/document/d/1XjXkzhs5ngM5cmyrmTLaIxG6TF4jT7-HMsMrjj3akRw/edit#heading=h.c5oaif5q8e2o) for name attributes to accompany NetID values. While we don't yet have everything set up as outlined in the [TigerData Role Eligibility Definitions document](https://docs.google.com/document/d/1OyOLTd_jMqszRbN_vPhAC_lDB-p4E8czxAGM55Z1FbU), I presume it is possible in the interim to query LDAP to retrieve names, given NetIDs. In any case, the idea is to retrieve names automatically (not via anyone's deliberate data entry).

### Completion Criteria
- [x] On the "Project Details" (show) page, under the "Roles" heading, the full name of each person assigned to each role type is displayed
- [x] Fetch the display name from the database object (it should be there already) 
- [x] If multiple persons are assigned to a given role, then on the "Project Details" page, the names of all persons in that role are displayed as a comma-separated list, sorted alphabetically by family name

**Comment by bess** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/265?planning-poker) with Zenhub @carolyncole @hectorcorrea @JaymeeH @leefaisonr
