### ISSUE TITLE
Connect development environment to local MediaFlux instance

### ISSUE THREAD

**Issue by kelynch** [pulibrary/tiger-data-app#27]
Connect development Rails environment to local instance of MediaFlux running in Docker.

**Comment by mccalluc** [comment]
- See also: #28

To make a connection, we need to know which credentials will be used to make that connection.
My sense from the meeting this morning is that this is unknown, but we'll learn more after the trainings next week:

> Bess: No we don’t have an answer… Think we heard from John Wiggins that we shouldn’t be doing local account management.
> Kate: Will be talking with Keith in OIT… He says there is info in LDAP that they can provide.
