### ISSUE TITLE
Project Details page - preliminary automatic settings

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/tiger-data-app#270]
### User Story
As a Data Sponsor, when I review the details of a given project, I need to see what parameters were set automatically, so I can understand what I'm able to do with the project and decide whether I need to request any changes.

### Notes
As of Dec. 13, we don't have an "Automatic Settings" section on the Project Details page (aka "show" page):
![TD_ProjectDetails_AutomaticSettingsInsert_2023-12-13](https://github.com/pulibrary/tiger-data-app/assets/66128387/d09fbd0d-3036-43cc-9107-56fc105f7350)

The goal is to have it look like the wireframe shown in the user journey from #247, i.e.:
![TD_ProjectDetails_AutomaticSettings_2023-12-13](https://github.com/pulibrary/tiger-data-app/assets/66128387/c8d7af79-e0b2-4611-a758-4f3697a8fc12)

In this preliminary phase, we are suppressing some required project metadata fields from the new project request form, but the [Standard Metadata Schema](https://docs.google.com/document/d/1XjXkzhs5ngM5cmyrmTLaIxG6TF4jT7-HMsMrjj3akRw) includes default values for 3 out of 4 that we want to include in the preliminary Project Details page: "Storage Capacity" ("500 GB"); "Storage Performance Expectations" ("Standard"); and "Project Purpose" ("Research"). The other field to display under "Automatic Settings" is "Project ID," for which #257 is meant to establish a process for automatic assignment. However, I don't think #257 needs to be a blocker for this issue; we can in the interim use placeholder values for Project IDs (e.g., 09az-0002).

I also do not want this issue to be a blocker for #287, though they are certainly related. If we can simply display all four of the automated settings on the "Project Details" page, even without including all of them in the metadata model, then I will be satisfied for now. But of course, in the future, we will need the metadata model to include all fields in the standard schema.

This issue is dependent on #264, which establishes all of the headings for the "Project Details" page

### Completion Criteria
Note there is no querying of mediaflux or tracking provenance here, ONLY taking data from a config file, saving it to the database, and displaying it on the screen

- [x] The preliminary "Project Details" page includes a section with the heading "Automatic Settings" below the "Description" section
- [x]  The "Automatic Settings" section includes 4 fields (in order): "Project ID"; "Storage Capacity"; "Storage Performance Expectations"; and "Project Purpose"
- [x] The "Project ID" value shown for a given project is the [draft DOI reserved for that project](https://github.com/pulibrary/tiger-data-app/issues/257)
- [x] Add database fields for storage_capacity_requested (string), storage_performance_expectations_requested (string), project_purpose (string)
- [x] There is a config file where these automatic values are managed
  - [x] The "Storage Capacity (Requested)" value is the default "500 GB"
  - [x] The "Storage Performance Expectations (Requested)" value is the default "Standard"
  - [x] The "Project Purpose" value is the default "Research"
- [x] The form sets these values from the default values in the config file
- [x] All of these values are displayed on the project show page

**Comment by bess** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/270?planning-poker) with Zenhub @carolyncole @hectorcorrea @JaymeeH @leefaisonr
