### ISSUE TITLE
Project Details page - preliminary provenance values

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/tiger-data-app#271]
### User Story
As a Data Sponsor, when I review my project's details, I need to see event markers for submission requests, along with the current status, so that I can fulfill my duty of project monitoring and decide whether any further action is required.

### Notes
We don't have all the details worked out yet for recording provenance in project metadata. The goal with this issue is to make a little progress by having a place to show key details to Data Sponsors on the Project Details page. I don't want this to be a blocker for #287, and it looks like some headway was already made in #264 and #302.

As of Dec. 13, I don't see a provenance section in staging yet:
![TD_ProjectDetails_ProvenanceInsert_2023-12-13](https://github.com/pulibrary/tiger-data-app/assets/66128387/b4e33f3c-0590-4bde-b5b2-ea60ddf96e23)

For new project requests covered by #113, we certainly have a way to record who submitted the request, and presumably we can record a timestamp of when that happened (please, always use the [ISO 8601 standard](https://en.wikipedia.org/wiki/ISO_8601) for all dates and times in metadata). When a new project is requested, the first status it receives is always "Pending".

We do not yet have a way to interoperate with other systems to automatically record project request approvals or update statuses from "Pending" to "Active". I suggest the way to keep moving forward in the meantime is to focus only on recording the submission request provenance.

### Completion Criteria
- [x] Create a rails class called ProvenanceEvent where these will be stored
- [x] The ProvenanceEvent has the following Fields:
       - Event Type [ "Submission", "Status Update" ]
       - Event Details [ see below criteria for submission ]
       - Event Person [ netid of the creator ]
       - Event timestamp [ timestamp on creation ]
- [x] The preliminary "Project Details" page includes a section with the heading "Provenance" below the "Automatic Settings" section
- [x] The "Provenance" section on the display includes 2 fields (in order): "Submission" and "Status"
      - Status is the current status
      - Submission is the list of Event Details for the Request and the Approval only
      - ![Screenshot 2024-01-17 at 11 24 21 AM](https://github.com/pulibrary/tiger-data-app/assets/65608/a24e87ae-58a0-4a49-a178-e5867de0b348)
- [x] Submission Event Details: The "Submission" field displays, for now, "Requested by [data sponsor name], [timestamp]", where [data sponsor name] is filled by the full name of the person who submitted the request form for that project and [timestamp] is filled by the ISO 8601-standardized date and time with time zone offset, as recorded by the server at the time of project request submission
- [x] Status Event Details: The Status was updated from [original] to [new]
- [x] When a Project form is submitted two Provenance Events are created Submission & Status

**Comment by bess** [comment]
![Screenshot 2024-01-17 at 11 24 21 AM](https://github.com/pulibrary/tiger-data-app/assets/65608/a24e87ae-58a0-4a49-a178-e5867de0b348)

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/271?planning-poker) with Zenhub @hectorcorrea @JaymeeH @jrgriffiniii @kelynch @leefaisonr @bess
