### ISSUE TITLE
Project Details page - edit buttons

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/tiger-data-app#273]
### User Story
As a Data Manager, when I review a project's current metadata and settings on the Project Details page, I need a clear indication of which sections I am permitted to edit, so that I can make any necessary changes quickly.

### Notes
Data Managers have some limited privileges to edit project attributes, in order to allow them to manage the day-to-day aspects of an ongoing project. These privileges include adding and removing Data Users (not changing the Data Sponsor or Data Manager), as well as editing the Description fields.

Data Sponsors also have full permissions to edit project attributes. Their user journey will be addressed later, but for now, the "Edit" buttons described in this issue apply to both Data Sponsors and Data Managers.

When the viewer of the Project Details page is the Data Manager or Data Sponsor for that project, they should see clickable "Edit" buttons next to the "Roles" and "Description" headings, like so:

![TD_ProjectDetails_EditButtons_2024-01-23](https://github.com/pulibrary/tiger-data-app/assets/66128387/9723df8b-bf39-4608-951c-b1d94e417d19)

Clicking an Edit button should take one to the "Project Revision Request" form, as detailed in #275.

### Completion Criteria

- [ ] If a project is still pending, no "Edit" buttons are shown
- [ ] If the project is active and the user is a Data Sponsor or Data Manager for the project, they can see "Edit" buttons next to the "Roles" and "Description" headings on the "Project Details" page
- [ ] Clicking either "Edit" button takes the user to the "Project Revision Request" (separate issue)

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/273?planning-poker) with Zenhub @bess @JaymeeH @jrgriffiniii @leefaisonr
