### ISSUE TITLE
Connect testing environment to MediaFlux staging

### ISSUE THREAD

**Issue by kelynch** [pulibrary/tiger-data-app#28]
Connect testing Rails environment to MediaFlux staging server.

**Comment by mccalluc** [comment]
To make a connection, we need to know which credentials will be used to make that connection.
My sense from the meeting this morning is that this is unknown, but we'll learn more after the trainings next week:

> Bess: No we don’t have an answer… Think we heard from John Wiggins that we shouldn’t be doing local account management.
> Kate: Will be talking with Keith in OIT… He says there is info in LDAP that they can provide.

**Comment by kelynch** [comment]
This ticket does not refer to identity management.  The meeting with Keith is not a blocker.  This ticket refers to setting up the Rails application to specifically point to the staging server that Robert and Rishi set up as part of the application configuration.  

If you need further direction or clarification, please reach out to me.

**Comment by kelynch** [comment]
See my comment on the above-linked testing ticket.  Paraphrasing for this ticket's particulars:

This ticket does not refer to identity management. The meeting with Keith is not a blocker. This ticket refers to setting up the Rails application to specifically point to the locally running MediaFlux instance using Docker as part of the application configuration for development.

If you need further direction or clarification, please reach out to me.
