### ISSUE TITLE
Create a training environment

### ISSUE THREAD

**Issue by bess** [pulibrary/tiger-data-app#280]
Because there will be training happening, and that training will need a place to happen, we need a tiger data environment that is not staging or production.

## Acceptance criteria
- [x] [2 servers: tiger-data-app-qa1 and tiger-data-app-qa2 (Ops ticket to create box)](https://github.com/pulibrary/princeton_ansible/issues/4554)
- [x] These hosts have been added to princeton_ansible (us once the box has been created)
- [x] Required software has been installed (run role in princeton_ansible)
- [x] Tiger data app can deploy to QA (Capistrano)
- [x] The app points to a different root on the staging instance of media flux (e.g. `td-qa` on td-meta1)

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/280?planning-poker) with Zenhub @hectorcorrea @JaymeeH @jrgriffiniii @leefaisonr @kelynch
