### ISSUE TITLE
Preliminary role value validation

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/tiger-data-app#285]
### User Story
As a Data Sponsor, when I am filling out the new project request form, I need all of the role fields to be validated before I am able to submit, so that I don't have to waste my time following up with the system administrators.

![TD_NewProjectForm_UserFields_2023-12-05](https://github.com/pulibrary/tiger-data-app/assets/66128387/5b15541a-9c56-4ca9-9bda-fb35854dc4ff)

### Notes
This issue follows up from #200.

In this preliminary phase, we not have all of the systems set up to centrally validate role eligibility (though we do have a plan laid out in [TigerData Role Eligibility Definitions](https://docs.google.com/document/d/1OyOLTd_jMqszRbN_vPhAC_lDB-p4E8czxAGM55Z1FbU)).

For now, what we have to do is validate against the [TigerData Preliminary Registration List](https://docs.google.com/spreadsheets/d/169lfRTOSe6H66Iu2DK5g-QzqiVsfz5lHFHMaGmwNT7Y), which is maintained by the PO. I might recommend that you periodically pull the NetIDs from that list and include them somewhere in your code base just to get us rolling, but I'll leave the specifics to you. All we really need right now is a very basic restriction of roles to persons we know about in the early adopter phase.

### Completion Criteria
- [ ] Use the NetIDs given in [TigerData Preliminary Registration List](https://docs.google.com/spreadsheets/d/169lfRTOSe6H66Iu2DK5g-QzqiVsfz5lHFHMaGmwNT7Y) as of Dec. 5, 2023 to define the preliminary registered users of TigerData
- [ ] For any role field (Data Sponsor, Data Manager, or Data User), verify that the values given are found among the preliminary registered users of TigerData
- [ ]  List can be open source.  Import a yml from google drive

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/285?planning-poker) with Zenhub @bess @hectorcorrea @JaymeeH @jrgriffiniii @kelynch @leefaisonr
