### ISSUE TITLE
Is version.txt needed?

### ISSUE THREAD

**Issue by mccalluc** [pulibrary/tiger-data-app#31]
Trying to follow the instructions on `rails-template`:
> Add the `write-version` task to give your project a public page at `/version.txt` with the branch name, commit SHA, and release date of the current deployment.

There is [no other reference](https://github.com/pulibrary/rails-template/search?q=write-version) to `write-version` in that repo, and I also can't find anything in `pdc-describe`.

If this is is something tiger-data should have, please clarify or point to an example. If it's not needed this can be closed. Perhaps remove the mention from `rails-template`.

**Comment by escowles** [comment]
This might be a reference to a Capistrano post-deploy task from some other project, like DPUL: https://github.com/pulibrary/dpul/blob/main/config/deploy.rb#L36
