### ISSUE TITLE
Add DataCite API keys to tiger data servers

### ISSUE THREAD

**Issue by bess** [pulibrary/tiger-data-app#325]
- [x] Staging and QA servers have the sandbox API key
- [x] Production has the production DataCite API key
- [x] Both systems have an environment variable for the DOI prefix. For now, use the same as PDC.
- [x] These are in the same environment variables we used for PDC 
- [x] These are in princeton ansible, and stored encrypted

**Comment by bess** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/325?planning-poker) with Zenhub @leefaisonr @carolyncole @JaymeeH @hectorcorrea

**Comment by carolyncole** [comment]
fixed by https://github.com/pulibrary/princeton_ansible/pull/4561
