### ISSUE TITLE
Add a field in the tigerdata metadata for the project id

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/tiger-data-app#336]
## Acceptance criteria
- [x] Add a project_id field to the project_schema_fields: https://github.com/pulibrary/tiger-data-app/blob/main/app/models/tigerdata_schema.rb#L39C5-L39C143
- [x] Modify [this script](https://github.com/pulibrary/tiger-data-app/blob/main/docs/schema_script.txt) and ask Robert Knight to add it to td-meta1 
- [x] Change the class that sends the XML to mediaflux (app/models/project_mediaflux#project_values)

**Comment by bess** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/336?planning-poker) with Zenhub @carolyncole @hectorcorrea @JaymeeH @leefaisonr
