### ISSUE TITLE
Create the Namespace xml and attach it to the create email

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/tiger-data-app#343]
The IT folks additionally want the XML for creating the Namespace.

As a follow up to #287

Acceptance criteria:

- [ ] Create the xml payload for [generating a new namepsace](https://github.com/pulibrary/tiger-data-app/blob/a40fcb21c066d1cd7c30edb4aef79bce0ac61307/app/models/project_mediaflux.rb#L11-L13)
- [ ] Attach the xml to the email sent on creation
- [ ] Add a route that you can see the namespace create in the application

**Comment by kelynch** [comment]
Unclear whether this is needed.  Closing this ticket.
