### ISSUE TITLE
API Authentication spike

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/tiger-data-app#35]
Can we authenticate via cas and devise for an API utilizing this article:
https://thinkster.io/tutorials/rails-json-api/setting-up-users-and-authentication-for-our-api

## Acceptance criteria
- [ ] Go through this tutorial and test whether it works
- [ ] Report back to the team
- [ ] If it works, password protect the `/api/v0/projects.json` endpoint in the app to require CAS authentication

**Comment by mccalluc** [comment]
After looking at this, my sense is that this tutorial and most others bring together two distinct things:
- Generate JWT 
- Checking the JWT on API routes

My sense is that with CAS, our application should not / can not generate the JWT: We should not be receiving the password: That should be a CAS API, and CAS should provide the JWT. Our application only checks the JWT.

At the meeting this morning, asked if we should ask OIT about this, and the answer was no. It would be good to clarify what we need to clarify on our side before we approach OIT: I'm not sure what the blocker is.

Other notes:
- What is actually going on under the hood? https://apereo.github.io/cas/6.6.x/installation/Configure-ServiceTicket-JWT.html
- JWT is one possible technology: I think OAuth is in the same space, and I think there are others.

**Comment by jrgriffiniii** [comment]
This has been deprecated over several API authentication sprints undertaken throughout the 2023 year.
