### ISSUE TITLE
Preliminary file inventory

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/tiger-data-app#384]
### User Story
As a Data User, I need to review an inventory of the files in one of my projects, so that I can orient myself and begin contributing.

### User Journey Images

![image](https://github.com/pulibrary/tiger-data-app/assets/66128387/0a4a0747-e5d7-467e-b29f-34df244f17e6)
![image](https://github.com/pulibrary/tiger-data-app/assets/66128387/c3bb640d-d965-4edc-8024-4c9abe6b0971)
![image](https://github.com/pulibrary/tiger-data-app/assets/66128387/e396ecf3-0cbe-452c-9d1d-3e7fe3e19549)
![image](https://github.com/pulibrary/tiger-data-app/assets/66128387/6de7716b-79e0-47ef-82ff-6da7f5184eaa)
![image](https://github.com/pulibrary/tiger-data-app/assets/66128387/a5277971-4e11-40d4-881f-3fd43b3a9c85)
![image](https://github.com/pulibrary/tiger-data-app/assets/66128387/fcf81fc7-4ed5-4467-a035-620179d0aafa)
![image](https://github.com/pulibrary/tiger-data-app/assets/66128387/f7cd6341-9e38-4bdf-a3d7-e951f07da5ec)
![image](https://github.com/pulibrary/tiger-data-app/assets/66128387/025c4048-1a25-481a-bc8b-7584f17ae62b)
![image](https://github.com/pulibrary/tiger-data-app/assets/66128387/fcfbcfa4-e7dd-4d27-a07a-b46326e13f25)
![image](https://github.com/pulibrary/tiger-data-app/assets/66128387/f4a4d5b0-26fa-4e3c-9e74-a40d3b45422a)
![image](https://github.com/pulibrary/tiger-data-app/assets/66128387/e4db9576-60ad-4a32-b5c1-2fb769665c44)
![image](https://github.com/pulibrary/tiger-data-app/assets/66128387/45019f98-e9bd-4b74-a9f2-84a3630cf1ae)
(Slides 28-39 in [TigerData_PresLayer_UserJourneys_v0.9_2024-01-24.pdf](https://drive.google.com/file/d/1qtAWMTLyJgQMqnM7qEM-fiDG3akxvUic/view?usp=drive_link))

### Completion Criteria
- [x] Tech setup
  - [x] #387 
  - [x] #388
- [ ] Spikes
  - [x] #392
  - [x] #393 
  - [x] #394 
  - [x] #395
  - [x] #398
- [x] #386 
- [ ] Create a new "Project Contents" page
  - [x] #389 
  - [x] #390 
  - [x] #391 
  - [ ] #397
  - [x] #396

**Comment by kelynch** [comment]
We may need to create additional tickets to reflect this in the UI.

**Comment by kelynch** [comment]
Make a "question" ticket to understand what is needed for the UI.  @bess will do this.
