### ISSUE TITLE
Add a “review contents” button to the project show page, which takes the user to the “project contents” page

### ISSUE THREAD

**Issue by bess** [pulibrary/tiger-data-app#386]
![Screenshot 2024-01-24 at 11 23 53 AM](https://github.com/pulibrary/tiger-data-app/assets/65608/75cce31f-4eaf-4420-8490-d4956936d100)

Possible implementations might build upon the following:
[collection query](https://github.com/pulibrary/tiger-data-app/blob/main/app/models/mediaflux/http/collection_query_request.rb)  or  [get metadata](https://github.com/pulibrary/tiger-data-app/blob/main/app/models/mediaflux/http/get_metadata_request.rb)

This assumes that the assignee will also implement the "Project Contents" page.
Also, we currently do not have any means by which to connect between Tiger Data App Project resources and Mediaflux Projects (which were created internally). Perhaps this could be queried and found using the Project path or DOI? Perhaps a script might be implemented in order to support this?
**There is currently no connectivity between the Mediaflux Projects and Tiger Data App Projects. This is scoped exclusively for the Tiger Data App (Rails), and as such, one must hard-code the Project ID. This is not blocked by #387**

Acceptance Criteria:
- [x] Have a button which links to the Project Contents View (including a test which proves this works)
- [x] Implement the Project Contents View to have the heading "Project Contents" (and nothing else)

**Comment by jrgriffiniii** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/386?planning-poker) with Zenhub @bess @carolyncole @hectorcorrea @JaymeeH @kelynch @leefaisonr @jrgriffiniii
