### ISSUE TITLE
Create a way to generate fake project files

### ISSUE THREAD

**Issue by bess** [pulibrary/tiger-data-app#387]
Create a way and document a process to generate a significant number of fake project files in our local mediaflux instances for testing purposes.

[The test asset create](https://github.com/pulibrary/tiger-data-app/blob/main/app/models/mediaflux/http/test_asset_create_request.rb)

## Acceptance criteria
- [ ] There is documentation in the README that team mates can follow
- [x] It makes around 1 Million files with several levels of directory hierarchy

**Comment by carolyncole** [comment]
We have not added the instructions yet...
