### ISSUE TITLE
Add a "show more" button to the project contents page

### ISSUE THREAD

**Issue by bess** [pulibrary/tiger-data-app#390]
Add a “show more” button that displays up to 100 files

![Screenshot 2024-01-24 at 11 30 33 AM](https://github.com/pulibrary/tiger-data-app/assets/65608/e6c99e52-f7ae-499d-b1e8-f8cb3b32a19e)

- Please note that DataTables does *not* have a tree view for the assets
- We may want more columns within the DataTables; There will need to be a research ticket for exploring additional metadata for the columns
  - This may include replacing DataTables
- aterm command: `asset.query :action get-name` or `asset.query :action get-meta`

Acceptance Criteria:
- [ ] This retrieves the second set of files from the Mediaflux server API
- [ ] If there are not more than 100 files, then the "Show More" button is in the disabled HTML state (greyed out)
- [ ] DataTables is updated with the second set of files retrieved from Mediaflux

**Comment by carolyncole** [comment]
values returned from `asset.get :action get-meta`
<img width="933" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd24rQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--85eccdb3ddc0a77ddd356634679852b84f7859d5/Screenshot%202024-01-25%20at%201.36.04%E2%80%AFPM.png" alt="Screenshot 2024-01-25 at 1.36.04 PM.png" />

**Comment by jrgriffiniii** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/390?planning-poker) with Zenhub @bess @carolyncole @hectorcorrea @JaymeeH @jrgriffiniii @leefaisonr
