### ISSUE TITLE
SPIKE: how to query mediaflux for file size range? 

### ISSUE THREAD

**Issue by bess** [pulibrary/tiger-data-app#392]
Goal: How hard is this to do? What approaches might we take?

![Screenshot 2024-01-24 at 11 33 50 AM](https://github.com/pulibrary/tiger-data-app/assets/65608/5d5e8932-8174-41f9-895f-c66f6ad903b1)

- We do need the answer to this in order to proceed with a Mediaflux Accumulator
- Spend up to a week
  - If one week is not enough time, there will need to be a team meeting held discussing the constraints for this issue

**Comment by carolyncole** [comment]
I will take about 8 seconds to query 200k records
```
td-meta1 >  asset.query :collection 1734250 :action range :xpath content/size
	:value -nbe "189050"
		:min "0"
		:max "345890"
```
