### ISSUE TITLE
SPIKE: how to query mediaflux for directory count and directory depth? 

### ISSUE THREAD

**Issue by bess** [pulibrary/tiger-data-app#394]
![Screenshot 2024-01-24 at 11 37 09 AM](https://github.com/pulibrary/tiger-data-app/assets/65608/321102e1-f701-468b-8121-e7c7a19cb683)

- This is extremely similar to #392 and #393, and the goal is to ensure that this is actually possible, and to determine how difficult this is to implement
- Scope one week for addressing this
- This directory should be easy, as the Accumulator gives client the number of assets and Collection assets (directories become assets)
- There is uncertainty as to how to find the directory depth
  - If this requires more than one week to determine the depth, then this might not be required immediately (no user has demanded this)

**Comment by carolyncole** [comment]
Returns almost immediately with all the paths.  A couple seconds on project g
```
"/princeton/tigerdata/projectg/1/7/7/3/17736/17736-h"
asset.query :collection 1734250 :action get-path  :where "type='application/arc-asset-collection'"
	:path -id "1734557" -version "1" "/princeton/tigerdata/projectg/1/7/7/3/17734"
	:path -id "1734631" -version "1" "/princeton/tigerdata/projectg/1/7/7/3/17734/17734-h"
	:path -id "1734698" -version "1" "/princeton/tigerdata/projectg/1/7/7/3/17737"
	:path -id "1734833" -version "1" "/princeton/tigerdata/projectg/1/7/7/3/17735"
	:path -id "1734861" -version "1" "/princeton/tigerdata/projectg/1/7/7/3/17735/17735-h"
	:path -id "1735001" -version "1" "/princeton/tigerdata/projectg/1/7/7/3/17738"
	:path -id "1735025" -version "1" "/princeton/tigerdata/projectg/1/7/7/3/17739"
	:path -id "1735129" -version "1" "/princeton/tigerdata/projectg/1/7/7/3/17732"
	:path -id "1735275" -version "1" "/princeton/tigerdata/projectg/1/7/7/3/17732/17732-h"
	:path -id "1735338" -version "1" "/princeton/tigerdata/projectg/1/7/7/3/17730"
	:path -id "1735349" -version "1" "/princeton/tigerdata/projectg/1/7/7/3/17730/17730-h"
```
