### ISSUE TITLE
SPIKE: how to query mediaflux for date modified range

### ISSUE THREAD

**Issue by bess** [pulibrary/tiger-data-app#395]
![Screenshot 2024-01-24 at 11 38 31 AM](https://github.com/pulibrary/tiger-data-app/assets/65608/d2a90f68-8171-4dcc-bc79-d59c1c8b3525)

- This is extremely similar to #392, #393, and #394, and the goal is to ensure that this is actually possible, and to determine how difficult this is to implement
- Scope one week for addressing this
- This may be another Accumulator (similar to the file size range)

**Comment by carolyncole** [comment]
This query takes about 8 seconds, but fulfills the request.
```
td-meta1 >  asset.query :collection 1734250 :action range :xpath mtime
	:value -nbe "215978"
		:min "Thu Nov 12 04:50:34 EST 1981"
		:max "Mon Mar 15 04:31:33 EDT 2021"
```
