### ISSUE TITLE
Add a “list all files” button which kicks off a “list all files” sidekiq job

### ISSUE THREAD

**Issue by bess** [pulibrary/tiger-data-app#397]
![Screenshot 2024-01-24 at 11 41 59 AM](https://github.com/pulibrary/tiger-data-app/assets/65608/612370ca-a248-4320-84de-e0176611addd)

![Screenshot 2024-01-24 at 11 42 51 AM](https://github.com/pulibrary/tiger-data-app/assets/65608/3f770285-2823-4fd9-ad98-b0e2ec50e1cd)

- This just initiates a sidekiq job, which is a placeholder for now
- The generation of the CSV is a separate ticket

Acceptance Criteria:
- [x] Add a “list all files” button which kicks off a “list all files” sidekiq job, which doesn’t yet do anything. 
- [x] It has a warning pop up that says “this will generate a CSV containing x number of files. Are you sure?”
- [x] It displays a message at the bottom of the project contents page telling you that you have a background job running
- [x] On the dashboard you have a “recent activity” section which lists the background jobs that have been requested and their status: 
  - [x] Requested at timestamp
  - [ ] Completed at timestamp

**Comment by jrgriffiniii** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/397?planning-poker) with Zenhub @bess @carolyncole @hectorcorrea @JaymeeH @jrgriffiniii @leefaisonr

**Comment by jrgriffiniii** [comment]
Currently for https://github.com/pulibrary/tiger-data-app/compare/i397-jrgriffiniii-sidekiq-list?expand=1, I have the following design and behavior implemented:

![image](https://github.com/pulibrary/tiger-data-app/assets/1443986/4dcd5c0b-c2c5-4388-bbf6-c09e4f37504f)
![image](https://github.com/pulibrary/tiger-data-app/assets/1443986/9e815683-df20-426d-8150-ce31aa7a353d)
![image](https://github.com/pulibrary/tiger-data-app/assets/1443986/799a71bd-7721-4207-8e8a-583d0628798c)
