### ISSUE TITLE
Should Vite also replace sprockets, and not just webpacker?

### ISSUE THREAD

**Issue by mccalluc** [pulibrary/tiger-data-app#40]
- Follow-up to #39

The concerns of Sprockets and Vite overlap... but they can co-exist, as the [migration guide](https://vite-ruby.netlify.app/guide/migration.html) points out:

> If you would like to remove sprockets and use Vite Ruby alone, you can [follow this example](https://github.com/ElMassimo/vite_ruby/pull/165).
> Have in mind that this is optional, as both approaches can coexist without issues.

For now, I will leave the required manifest in place. Removing spockets gets a little complicated because we need to move from just using all of Rails to selecting [just those that we are using](https://github.com/ElMassimo/vite_ruby/pull/165/files#diff-b06d1978289e5889ba2ae88fc357b0b31b43639ebc9156a63b651ab4d5e6134b).

**Comment by carolyncole** [comment]
We decided in the meeting, to just utilize vite for javascript, and keep sprockets for other assets.

**Comment by mccalluc** [comment]
so this can be closed.
