### ISSUE TITLE
Add role columns from User Registration List to the User model

### ISSUE THREAD

**Issue by leefaisonr** [pulibrary/tiger-data-app#415]
Completion Criteria: 

- [x] User model has fields for `eligible_sponsor` and `eligible_manager` 
- [x] User model is populated when user registration csv is loaded 
- [ ] Factory for user has the ability to create `eligible_sponsor` and `eligible_manager` users

**Comment by bess** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/415?planning-poker) with Zenhub @bess @hectorcorrea @JaymeeH @jrgriffiniii @leefaisonr
