### ISSUE TITLE
Integrate mediaflux into our CI build

### ISSUE THREAD

**Issue by bess** [pulibrary/tiger-data-app#428]
I believe we can integrate mediaflux into our CI build by:
1. put our mediaflux docker image onto a private dockerhub 
2. use docker-compose to build a multi-container orchestration of  cimg/ruby:3.1.3-browsers, postgres:13.5-alpine, and mediaflux for local development
3. use docker-compose for circle ci

**Comment by bess** [comment]
First I tried pushing our mediaflux image to a private dockerhub account and incorporating it into the CI build. This worked, except that the docker image does not publish to port 8888 by default, we are doing that via the `$ docker create --name mediaflux --publish 0.0.0.0:8888:8888 princeton_dev:23.08.25` command, and I don't see a way to add that `--publish` bit into the circleci config. What we end up with is an instance of mediaflux that we can't talk to. 

![Screenshot 2024-02-05 at 4 39 25 PM](https://github.com/pulibrary/tiger-data-app/assets/65608/bd65fcec-764b-48ce-ae56-9ccf0dfbb035)


![Screenshot 2024-02-05 at 4 21 03 PM](https://github.com/pulibrary/tiger-data-app/assets/65608/58f52faf-2741-4e64-8b1c-708702030f8f)

**Comment by bess** [comment]
How to dockerize a rails application: https://semaphoreci.com/community/tutorials/dockerizing-a-ruby-on-rails-application

Then I think we could use docker-compose to bring up mediaflux beside our rails app on circleci.

**Comment by bess** [comment]
Carolyn found this: 
> If you start up that conatiner in any other way than in our documentation you get and error arc.mf.licence.ExInvalidLicence: The licence at file:/usr/local/mediaflux/config/licence.xml cannot be used: not a licence for this host. Expected '02:42:ac:11:00:02' but found the following ids [02:42:ac:11:00:03]

**Comment by bess** [comment]
I'm putting this down for now until we get more clarity about whether this will be possible.

**Comment by carolyncole** [comment]
https://circleci.com/docs/building-docker-images/#run-docker-commands-using-the-docker-executor may help

**Comment by carolyncole** [comment]
I did a bit of work on this yesterday afternoon.  I was able to get mediaflux to run in circle ci, but could not get the network to connect... https://github.com/pulibrary/tiger-data-app/blob/mediaflux-in-ci-cac/.circleci/config.yml#L72-L74

**Comment by kelynch** [comment]
Matt and Chuck will look into a recommended approach.  Putting this on hold for the moment.
