### ISSUE TITLE
Mediaflux::Http::Query only returns items in the top level when a collection is applied

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/tiger-data-app#430]
When you query in Aterm with `asset.query :collection 1734250` you get any item in the collection or it's sub-collections.  Our code claims to mimic that but it only returns items at the top level of the collection.

I created a PR #429 to address this issue, but there were objections to the PR.

**Comment by jrgriffiniii** [comment]
Iterators rather than cursors are being used, and hence this might no longer be necessary.

**Comment by hectorcorrea** [comment]
I guess we could default our code to do a `deep_search` but I don't see the gain one way or another. I suggest we close this.
