### ISSUE TITLE
Refactor our mediaflux Namespace/Collection hierarchy to match RC/Chuck's 

### ISSUE THREAD

**Issue by JaymeeH** [pulibrary/tiger-data-app#432]
As of right now, our local Mediaflux instance creates Collections (projects) to be children of Namespaces. They should instead have a 'cousin' relationship as opposed to a parent-child relationship.

Our structure will be as follows (notice the `/td-demo-001NS` cousin for namespaces):

```
/td-demo-001 (namespace)
/td-demo-001/project1 (collection)
/td-demo-001/project1 (collection)
/td-demo-001NS (namespace)
/td-demo-001NS/project1NS (namespace)
/td-demo-001NS/project2NS (namespace)
```

Notice that this mimics the structure of Mediaflux in production but this is **not** the structure used for `projectg` in the staging environment (`td-meta1`). 

We have code in our ProjectMediaflux class to create the rootnamespace that will need to be updated: https://github.com/pulibrary/tiger-data-app/blob/4ea19f3ffdb4a76a2587387fea3a20e9e67ca20a/app/models/project_mediaflux.rb#L72 

And also the code that sets the "project_namespace" on the same class: https://github.com/pulibrary/tiger-data-app/blob/4ea19f3ffdb4a76a2587387fea3a20e9e67ca20a/app/models/project_mediaflux.rb#L12

Acceptance Criteria
- [ ] The Collection for a project is created at within td-demo-001 and Namespace for a project is created under td-demo-001NS

**Comment by hectorcorrea** [comment]
Below is how projects are structured in production which is the model that we want to follow:

![Screenshot 2024-02-02 at 3 14 39 PM](https://github.com/pulibrary/tiger-data-app/assets/568286/a68f4759-107f-487f-bfa0-7d923d3c9462)

**Comment by jrgriffiniii** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/432?planning-poker) with Zenhub @hectorcorrea @JaymeeH @jrgriffiniii @leefaisonr
