### ISSUE TITLE
Create a form where Chuck can enter a project ID

### ISSUE THREAD

**Issue by bess** [pulibrary/tiger-data-app#443]
The dashboard for system administrators should allow the entry of a mediaflux_id to associate a mediaflux project with a Rails Project object. This will fulfill the decision recorded in #442 (ADR for storing mediaflux collection ID in the front end). 

When a mediaflux admin manually creates a project they need to be able to go to a form that will let them enter the mediaflux id and attach it as the project.mediaflux_id

Acceptance Criteria:
- [x] Design a form which provides a user with the ability to provide a Mediaflux ID for an existing Project
- [x] Upon submitting the form, ensure that the `ProjectsController` links the Mediaflux ID to the existing Project (using something similar to `project.mediaflux_id = params[:mediaflux_id]`)
- [x] Ensure that this dashboard is only accessible to authenticated users with the `system administrator` role
- [x] Ensure that there is a button (for `system administrator` users) on the form which directs users to the Mediaflux ID form from the Project show view
- [x] Ensure that there is a button on the Mediaflux ID form which can link back to the Project show view

**Comment by jrgriffiniii** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/443?planning-poker) with Zenhub @hectorcorrea @JaymeeH @leefaisonr @jrgriffiniii
