### ISSUE TITLE
Add two new columns to user management spreadsheet

### ISSUE THREAD

**Issue by bess** [pulibrary/tiger-data-app#446]
We have two more roles for users: superuser (basically, the tiger data development team) and sysadmin (OIT staff like Chuck who need a different interface so they can approve projects). 

### Acceptance criteria
- [x] Matt needs to actually add the columns and populate them (or approve our first pass)
- [x] Create database columns on the User model for superuser and sysadmin
- [x] Populate those columns when we refresh the spreadsheet data

**Comment by bess** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/446?planning-poker) with Zenhub @carolyncole @hectorcorrea @JaymeeH @jrgriffiniii @leefaisonr

**Comment by matthewjchandler** [comment]
I'm fine with the columns as added today by RDSS. I also added a couple more folks from Research Computing as sysadmins: https://docs.google.com/spreadsheets/d/169lfRTOSe6H66Iu2DK5g-QzqiVsfz5lHFHMaGmwNT7Y
