### ISSUE TITLE
Clean up mediaflux test data

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/tiger-data-app#452]
We need a way to clean up the data being created by the tests that hit our local Mediaflux instance.

`asset.destroy` should do it...

This code should only be available to the tests or run in the test environment. Please note that https://github.com/pulibrary/tiger-data-app/blob/main/app/models/mediaflux/http/get_metadata_request.rb is an example upon which to base the design of the new `asset.destroy` class.

Acceptance Criteria:
- [x] Implement as a `rake` Task which runs exclusively for test suites
- [x] Ensure that `RSpec` suites invoke this `rake` Task before and after all test suites
- [x] Implement the Mediaflux class supporting the Mediaflux `asset.destroy` command

**Comment by jrgriffiniii** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/452?planning-poker) with Zenhub @hectorcorrea @JaymeeH @jrgriffiniii @leefaisonr

**Comment by JaymeeH** [comment]
Note: We are not deleting Namespaces in this ticket. We may do so eventually in the future — but as of right now, test suites generating namespaces does not cause an error for duplicate names.
