### ISSUE TITLE
[Honeybadger] Improve error handling for Project Creation when Redis Failures are encountered

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/tiger-data-app#477]
Please see the following example: https://app.honeybadger.io/projects/113559/faults/104746997#notice-trace

In cases such as these, even if the Redis outage is not related to the Ruby on Rails codebase architecture, there might still be a need to improve error handling for end-users. For example:

```ruby
def create
    new_project
    project_metadata = ProjectMetadata.new( current_user:, project: new_project)
    new_project_params = params.dup
    metadata_params = new_project_params.merge({
      status: Project::PENDING_STATUS
    })
    project_metadata.create(params: metadata_params)
    if new_project.save
      TigerdataMailer.with(project: @project).project_creation.deliver_later
      redirect_to project_confirmation_path(@project)
    else
      render :new
    end
  rescue RedisClient::CannotConnectError => redis_client_error
    error_message = "Failed to create the new project: Failed to connect to the Redis client: #{redis_client_error}"
    Rails.logger.error(error_message)
    flash[:notice] = error_message
    render :new
  end
```

for https://github.com/pulibrary/tiger-data-app/blob/main/app/controllers/projects_controller.rb#L14

Acceptance Criteria:

- [x] Ensure that errors of the type `RedisClient::CannotConnectError` are properly handled from within `ProjectsController#create`
- [x] This error must be logged
- [x] The user should be aware that an error occurred when trying to create the new project

**Comment by jrgriffiniii** [comment]
Perhaps this needs to be restructured to reflect that users will need to repeatedly retry to create a new project (and if Redis is down, second attempts will still fail).

**Comment by kelynch** [comment]
Make sure that errors also go to Honeybadger.  Otherwise, this looks good.
