### ISSUE TITLE
Project schema in Mediaflux

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/tiger-data-app#490]
We should update our code to create the schema using the same definitions used by Chuck in `td-meta1`. Notice that their are using `CamelCase` instead of `snake_case` for the properties.

~~We probably want to wait on this until Matt and Chuck are back, though.~~

![td-meta1-schema](https://github.com/pulibrary/tiger-data-app/assets/568286/c20fa282-eb54-4f41-a833-1d94b5006c95)

**Comment by carolyncole** [comment]
The camel case field names more closely match the [google doc with the schema](https://docs.google.com/document/d/1XjXkzhs5ngM5cmyrmTLaIxG6TF4jT7-HMsMrjj3akRw/edit#heading=h.jyc9l9aomuz)
