### ISSUE TITLE
Standardize time zone

### ISSUE THREAD

**Issue by bess** [pulibrary/tiger-data-app#498]
Currently we're using EST (Eastern Standard Time) (e.g.: `Time.zone.parse(mf_date).in_time_zone("EST").strftime("%Y-%m-%dT%H:%M:%S%:z")`) Seems like this might cause problems during Eastern Daylight Time -- our time stamps will be off by an hour. 

However, just using `ET` (Eastern Time) doesn't work. 

Maybe we want to use `American/New York` instead, like this? https://github.com/pulibrary/tiger-data-app/blob/c93e7b24376c78ec99dc3d0883fee032e7424b03/app/views/projects/show.html.erb#L79

### Acceptance criteria
- [x] Decide on an approach 
- [x] Document the decision in an ADR
- [ ] Implement it the same way everywhere we're using timestamps

**Comment by kelynch** [comment]
Decided to use "American/New York" as the approach.
