### ISSUE TITLE
Write tests for destroying mediaflux iterators and remove the nocov tags associated with them

### ISSUE THREAD

**Issue by JaymeeH** [pulibrary/tiger-data-app#500]
- [ ] Write tests for `app/models/mediaflux/http/iterator_destroy_request.rb` and remove the `:nocov:` tag around the model class
- [ ] write a test for the `save_in_mediaflux` method in  `app/models/project.rb` and remove the `:nocov:` tag around the method

**Comment by hectorcorrea** [comment]
This has been addressed in PR https://github.com/pulibrary/tiger-data-app/pull/493
