### ISSUE TITLE
Test TigerData with real projects in td-meta1

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/tiger-data-app#501]
Now that we have a mechanism to link a TigerData project to a Mediaflux collection (see https://github.com/pulibrary/tiger-data-app/issues/443) we should deploy TigerData to staging in order to test with real projects (see https://github.com/pulibrary/tiger-data-app/issues/384)

**Comment by kelynch** [comment]
We cannot work this until Chuck is back and restores our access to the test collection "projectg."

**Comment by hectorcorrea** [comment]
`projectg` is now back again available on `td-meta1`

![Screenshot 2024-02-21 at 12 06 23 PM](https://github.com/pulibrary/tiger-data-app/assets/568286/bcf7997d-7f44-440d-950e-bcd5d36ad4ed)

**Comment by JaymeeH** [comment]
**Attempting to link `projectg` to a rails project through the `sysadmin dashboard` for approving projects**
![Screenshot 2024-02-23 at 3 16 05 PM](https://github.com/pulibrary/tiger-data-app/assets/54775395/b4322435-94e3-456f-8e62-82391bc6e23e)

**Link successful: NOTE: do we want to submit a project revision request when an admin approves a project?**
![Screenshot 2024-02-23 at 3 16 17 PM](https://github.com/pulibrary/tiger-data-app/assets/54775395/c350d037-cce4-4ddd-9a34-f1536ae99171)

**Able to view `projectg` files through the review contents page**
![Screenshot 2024-02-23 at 3 17 26 PM](https://github.com/pulibrary/tiger-data-app/assets/54775395/06777359-a593-4878-96f9-a280d8a21418)

**Able to click show more for an expanded view of `projectg` files**
![Screenshot 2024-02-23 at 3 17 38 PM](https://github.com/pulibrary/tiger-data-app/assets/54775395/69a75c12-18ac-4c86-a57c-656a3ff39d85)

**Requesting a file inventory for `projectg`**
![Screenshot 2024-02-23 at 3 17 45 PM](https://github.com/pulibrary/tiger-data-app/assets/54775395/6524ea5e-3ffa-465e-8c00-8739b08c3a89)

**Request Successful**
![Screenshot 2024-02-23 at 3 17 51 PM](https://github.com/pulibrary/tiger-data-app/assets/54775395/ddeaf317-11fd-40db-91e1-b9e269875731)

**Request Fulfilled and completed. Inventory available for download. NOTE: Background job for projectg takes approximately 8 minutes to be completed**
![Screenshot 2024-02-23 at 3 36 51 PM](https://github.com/pulibrary/tiger-data-app/assets/54775395/84a5710b-6bed-49fa-b2d5-a5f08da124ae)

**Able to download and view the file inventory for `projectg` as a csv**
![Screenshot 2024-02-23 at 3 36 57 PM](https://github.com/pulibrary/tiger-data-app/assets/54775395/457edb28-ad47-464a-a471-e2c1a77dd33d)

**Comment by JaymeeH** [comment]
@hectorcorrea can you take a look through my comments above about testing tigerdata with `projectg` and let me know if there is anything else that should be tested within tigerdata?

**Comment by hectorcorrea** [comment]
@JaymeeH We are still missing the accumulators for that project so that the "project summary" section at the top of the Contents page displays the data. They never existed for this project but we can ask Chuck to add them so that we can see the data and display it.

**Comment by JaymeeH** [comment]
@matthewjchandler How do you feel about system administrators being redirected to the project revision request page? Should a revision request be made when a project is approved, or should we just update the appropriate fields in tigerdata? Also, I was wondering if we should also be creating a provenance event for when a project gets approved

**Comment by hectorcorrea** [comment]
Closing in favor of https://github.com/pulibrary/tiger-data-app/issues/537 and https://github.com/pulibrary/tiger-data-app/issues/538
