### ISSUE TITLE
[HoneyBadger] TigerdataMailer#project_creation raises ArgumentError

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/tiger-data-app#513]
`TigerdataMailer#project_creation` raises `ArgumentError: wrong number of arguments (given 1, expected 0)` when invoked (following the deployment from https://github.com/pulibrary/tiger-data-app/compare/8467b9ef5d9dd60ebd775946971999ed1f97db11...36f69f16201d4d573ddbcff7ec46b17f78cebc55).

## Backtrace

    line 3 of [PROJECT_ROOT]/app/mailers/tigerdata_mailer.rb: project_creation

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/113559/faults/104876397)

**Comment by carolyncole** [comment]
I think this is related to some testing I was doing for the mail last week.  I forgot to send the parameters in with.
