### ISSUE TITLE
When redis is down, send detailed errors to honeybadger

### ISSUE THREAD

**Issue by bess** [pulibrary/tiger-data-app#514]
Currently, if redis is down, the mail that is supposed to go out won't go out. We will log in honeybadger the fact that redis was down, but we will lose the message and someone won't get an email. 

## Acceptance criteria
- [x] Create a custom error class to send to honeybadger in addition to the "redis down" message - something that makes it clear that an email wasn't sent
- [x] The error should contain enough information in it that we can re-create the email: who it should have gone to and what the message should have been

**Comment by hectorcorrea** [comment]
A first step could be to make sure we log enough information to know what project the error was for.

**Comment by kelynch** [comment]
Short-term: log errors in Honeybadger with a custom error type and enough information to know what project the error was raised for, and check on these as part of runner tasks in RDSS, especially if/when Redis goes down.

Keep in mind how often Redis goes down.

**Comment by leefaisonr** [comment]
It looks like this has been done already: https://github.com/pulibrary/tiger-data-app/blob/main/app/controllers/projects_controller.rb#L21C5-L44C35
