### ISSUE TITLE
Redis is down in staging

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/tiger-data-app#532]
Honeybadger reported that Redis is down in staging (https://app.honeybadger.io/projects/113559/faults/104742469) and we noticed that it stayed down for hours. Still is down.

We need to figure out how to restart it and how to make sure it restarts on its own if it goes down again.

We also noticed that Redis was down for PDC Describe (https://app.honeybadger.io/projects/99214/faults/102905699) and we think this might be related but given that each server runs its own Redis locally that might not be the case.

Acceptance criteria:

- [x] run the [new playbook](https://github.com/pulibrary/princeton_ansible/issues/4707) on tigerdata-staging1 /2 & tigerdata-prod1 /2

**Comment by carolyncole** [comment]
Looking in the logs redis shut down for some odd reason.  It looks like something shut it down...
```
57370:signal-handler (1708950275) Received SIGTERM scheduling shutdown...
57370:M 26 Feb 2024 12:24:36.034 * User requested shutdown...
57370:M 26 Feb 2024 12:24:36.034 * Saving the final RDB snapshot before exiting.
57370:M 26 Feb 2024 12:24:36.044 * DB saved on disk
57370:M 26 Feb 2024 12:24:36.044 * Removing the pid file.
57370:M 26 Feb 2024 12:24:36.044 # Redis is now ready to exit, bye bye...
```

**Comment by carolyncole** [comment]
Prod had the same issue this morning

```
31554:signal-handler (1709035774) Received SIGTERM scheduling shutdown...
31554:M 27 Feb 2024 12:09:34.351 * User requested shutdown...
31554:M 27 Feb 2024 12:09:34.351 * Saving the final RDB snapshot before exiting.
31554:M 27 Feb 2024 12:09:34.360 * DB saved on disk
31554:M 27 Feb 2024 12:09:34.360 * Removing the pid file.
31554:M 27 Feb 2024 12:09:34.360 # Redis is now ready to exit, bye bye...
```

**Comment by hectorcorrea** [comment]
@carolyncole restarted the redis server on each box with the following command

```
sudo service redis-server restart
```

**Comment by hectorcorrea** [comment]
Francis noted that until recently our redis did not automatically restarted on reboot: https://github.com/pulibrary/princeton_ansible/pull/4629.

**Comment by hectorcorrea** [comment]
We also ran to make sure it was enabled as a service

```
sudo systemctl enable redis-server
```

**Comment by hectorcorrea** [comment]
This can be closed one this has been implemented: https://github.com/pulibrary/princeton_ansible/issues/4707

**Comment by carolyncole** [comment]
Ran this code on staging and prod machines https://github.com/pulibrary/princeton_ansible/pull/4711
