### ISSUE TITLE
Accumulators for projects in td-meta1

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/tiger-data-app#537]
Make sure we can read the accumulators defined for projects in `td-meta1`. Our current test project `projectg` has some accumulators defined but we are not able to view them with our accounts.

Currently we see this:

```
> asset.collection.accumulator.describe :id 1734250 
    :asset -id "1734250"
```

But Chuck can view the accumulators defined and their values:

```
> asset.collection.accumulator.describe :id 1734250 
	:asset -id "1734250"
		:accumulator -type "collection.asset.count" -name "projectg-count"
			:stime "10313941"
			:value
				:collections "0"
				:non-collections "-1"
		:accumulator -type "content.all.size" -name "projectg-size"
			:stime "10527031"
			:value
				:total -count "189050" -count-zero "2" -h "106.761 GB" "106760739577"
```
Acceptance Criteria

- [x]  Send Chuck an email with all devs and the service account
- [x]  Make sure we can see them

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/537?planning-poker) with Zenhub @bess @JaymeeH @jrgriffiniii @leefaisonr

**Comment by hectorcorrea** [comment]
Chuck has granted our accounts access to the accumulators. This is what I see with my account on `td-meta1`

```
td-meta1 > asset.collection.accumulator.describe :id 2961340
    :asset -id "2961340"
        :accumulator -type "collection.asset.count" -name "projectg-count"
            :stime "11556489"
            :value
                :collections "26926"
                :non-collections "189060"
        :accumulator -type "content.all.size" -name "projectg-size"
            :stime "11556489"
            :value
                :total -count "189060" -count-zero "2" -h "106.781 GB" "106781219577"
```

He still needs to add it to the `tigerdataapp` account.

**Comment by JaymeeH** [comment]
RDSS Devs now have access to accumulators in staging (Querying the accumulators for `projectg` in staging)
 <img width="1279" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzJlQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3ea17d413e7dd6b2f79f23f0dd67a67aeebca51c/Screenshot%202024-02-29%20at%2010.11.44%E2%80%AFAM.png" alt="Screenshot 2024-02-29 at 10.11.44 AM.png" />

**Comment by JaymeeH** [comment]
Tigerdata service account has been granted access to accumulators in staging, allowing the app to display file count & size through querying the accumulators for the project
<img width="1495" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL21lQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e371e1a2bc1ddd95ee214792d165989a4be159e5/Screenshot%202024-02-29%20at%2010.15.02%E2%80%AFAM.png" alt="Screenshot 2024-02-29 at 10.15.02 AM.png" />
