### ISSUE TITLE
Spike What timezone is mediaflux using

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/tiger-data-app#539]
We need to verify where the timezone comes from for the dates in mediaflux.

We hope they are utilizing unix time, but lets check

Acceptance criteria

- [x] Document where the time zone comes from in Mediaflux in the Time Zone ADR

**Comment by carolyncole** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/539?planning-poker) with Zenhub @hectorcorrea

**Comment by JaymeeH** [comment]
After querying a collection through Aterm — the timezone for the automatic date settings in Mediaflux seems to be `Etc/UTC` with no `gmt offset`. 
<img width="348" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUtnQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6d33c172f6a5a5aa2955e13f50ec46d323196578/Screenshot%202024-02-29%20at%201.25.24%E2%80%AFPM.png" alt="Screenshot 2024-02-29 at 1.25.24 PM.png" />

<img width="1341" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVdnQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d1892def869fa2b7b7cae14a4731b77302c34646/Screenshot%202024-02-29%20at%201.24.51%E2%80%AFPM.png" alt="Screenshot 2024-02-29 at 1.24.51 PM.png" />



NOTE: there is no difference between time zones UTC and Etc/UTC

`Etc/UTC` is a timezone in the Olson-timezone-database (tz database), also known as IANA-timezones-database, in which all timezones conform to a uniform naming convention: Area/Location

Some timezones cannot be attributed to any Area of the world (think continents or oceans). Thus, the special Area `Etc` (Etcetera) was introduced. Area `Etc` applies mainly to administrative timezones such as `UTC`.
