### ISSUE TITLE
Add the metadata schema version as part of the tigerdata metadata schema

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/tiger-data-app#540]
We need to add a field to the schema to say what version of schema this is matching up

Acceptance Criteria:

- [ ] The current metadata version is known by the system as a string number "0.5" is the current version
- [ ] Commit the schema version in a `mediaflux_schema` folder in github with the version number
- [ ] Add a url to the schema in github
- [ ] Add a field to tigerdata metadata json to store that 
- [ ] Add field into tigerdata schema to pass the information to mediaflux

**Comment by bess** [comment]
This was accomplished as part of schema 6.1
