### ISSUE TITLE
Cleaning exported files

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/tiger-data-app#542]
With PR https://github.com/pulibrary/tiger-data-app/pull/530 we are going to start saving files generated by the user to a shared location, which allows users to download them regardless of what server produced the file (see https://github.com/pulibrary/tiger-data-app/issues/523)

We should come up with a process to decide when to delete those files:
* Should we delete them as soon as the user downloads the file?
* Should we delete them after X number of days (regardless of whether the user downloads them or not)?
* Other ideas

PR https://github.com/pulibrary/tiger-data-app/pull/530 added a rake task to delete these files, but we need to run the rake task manually. 

Completion Criteria
- [x] Keep it for one week at the longest
- [x] Keep it until I have done two more further file inventories.  Aka they requested the complete list two more times.
- [x] Remove the download link from recent activity that has been deleted

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/542?planning-poker) with Zenhub @JaymeeH @jrgriffiniii @kelynch @leefaisonr
