### ISSUE TITLE
Gather scripts from Chuck for creating the project

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/tiger-data-app#562]
Gather and Document the process scripts from Chuck, it may be just watching a video and create documentation.

- [ ] Ping Chuck to see if there any new steps the video does not have
- [ ] Document [steps in video](https://drive.google.com/file/d/1fYGNkVM9J94J1jUmZ7p0MZEUX2meLZav/view) in  docs/mediaflux_project_steps.md
- [ ] Compare with our current test creation and ticket difference

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/562?planning-poker) with Zenhub @bess @JaymeeH @jrgriffiniii @kelynch @leefaisonr

**Comment by carolyncole** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/562?planning-poker) with Zenhub @hectorcorrea

**Comment by hectorcorrea** [comment]
See also the `project:create_script` rake task introduced in: https://github.com/pulibrary/tiger-data-app/pull/582
