### ISSUE TITLE
Project G metadata needs in QA

### ISSUE THREAD

**Issue by kelynch** [pulibrary/tiger-data-app#564]
Update project g (created in #561) with the following information:

- [x] Kate as Data Sponsor and Data Manager for this
- [x] Matt as Data User
- [x] Title: "Project Gutenberg"
- [x] Directory: "projectg"
- [x] Description: "Demo sample of Project Gutenberg (not complete project)"
- [x] Quota should be set to whatever the usage is -- check with Chuck to ensure this is done, but check if we can do this ourselves first

Has about 215k files, for reference

**Comment by kelynch** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/564?planning-poker) with Zenhub @carolyncole @bess @hectorcorrea @JaymeeH @jrgriffiniii

**Comment by jrgriffiniii** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/564?planning-poker) with Zenhub @kelynch

**Comment by JaymeeH** [comment]
Quota: 
Ran 
```
> asset.collection.quota.set :id 1083 :quota 
     < :allocation 500 GB :on-overflow fail :description "500 GB quota for 1083" >
```
In the QA Aterm server
