### ISSUE TITLE
Script out the demo for March 26

### ISSUE THREAD

**Issue by kelynch** [pulibrary/tiger-data-app#565]
Plan and document the steps for file inventory demo to TigerData Steering on March 26.

Builds on #563

**Comment by hectorcorrea** [comment]
@kelynch FYI -- There is significant progress in #563 for this now.

**Comment by kelynch** [comment]
Thanks @hectorcorrea, @carolyncole, @leefaisonr ; I'm working on the script now here - https://docs.google.com/document/d/10Th28d-moGBZJykJbNMq2mZMcKLX5VPjExw-raH7Hog/edit

**Comment by kelynch** [comment]
So far so good, it looks like there may be a bug, I've created a ticket here - https://github.com/pulibrary/tiger-data-app/issues/595
