### ISSUE TITLE
Re-think time zone approach

### ISSUE THREAD

**Issue by bess** [pulibrary/tiger-data-app#568]
When we wrote our timezone ADR we thought that mediaflux ALWAYS reported time in UTC, and did not include timezone data on the dates it sends us. This is not the case. Mediaflux uses UTC for the internal system time but will report a timestamp based on the user's session. For example, here is Robert Knight querying aterm and getting a `US/Pacific` timezone:

<img width="854" alt="Screenshot 2024-03-13 at 2 42 25 PM" src="https://github.com/pulibrary/tiger-data-app/assets/65608/1041a2f8-a8ff-4d75-aa1e-0ba2934ecc21">

I believe we should be checking the timezone when we get dates from mediaflux, and adjusting the timezone and formatting in a consistent way across the application. Maybe a `MediafluxTime` class that takes a whole snip from mediaflux and gives back an America/New_York and iso time format? 

![Screenshot 2024-03-13 at 2 32 30 PM](https://github.com/pulibrary/tiger-data-app/assets/65608/1d3f1d7d-d609-4c2f-90dd-da931c47f1d9)

**Comment by JaymeeH** [comment]
I ssh'd into the mediaflux docker container to change the servers timezone
```
ls -l /etc/localtime
rm -rf /etc/localtime
ln -s /usr/share/zoneinfo/America/New_York /etc/localtime
```
```
date
'Notice the west coast `PDT` timezone'
```
<img width="882" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOW5wQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--182601bc707690086927d2e535141ccd9773b705/Screenshot%202024-05-16%20at%2012.38.27%E2%80%AFPM.png" alt="Screenshot 2024-05-16 at 12.38.27 PM.png" />

```
Then I created an asset in mediaflux
notice the 7 hour time difference: conversion to UTC
```
<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXZwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a66eb1162741c36b84eca59f92fae1f325005db9/Screenshot%202024-05-16%20at%2012.11.04%E2%80%AFPM.png" alt="Screenshot 2024-05-16 at 12.11.04 PM.png" />



```
I also queried the collection through aterm
again notice the 7 hour time difference: conversion to UTC
```
<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTNwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--306050b01d271c4e8324f7e0d17dfb03f4401fcc/Screenshot%202024-05-16%20at%2012.11.12%E2%80%AFPM.png" alt="Screenshot 2024-05-16 at 12.11.12 PM.png" />
