### ISSUE TITLE
Metadata schema spike

### ISSUE THREAD

**Issue by mccalluc** [pulibrary/tiger-data-app#57]
From Bess:

> 1) Getting the current definition of the metadata schema
> 2) Creating an object with that metadata schema
> 3) Updating to a new definition of the metadata schema

Connected to 
* #50

**Comment by matthewjchandler** [comment]
I suggest we complete our review of my Presentation Layer Core Functionality slide deck, and then begin this spike. It will be a natural progression.

**Comment by bess** [comment]
Closing in favor of:
* #60
