### ISSUE TITLE
Codify the preliminary System Administrator role

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/tiger-data-app#570]
### Context
At the beginning of our work, we discussed the roadmap for a full suite of roles in TigerData, one of them being the "System Adminsitrator."

![image](https://github.com/pulibrary/tiger-data-app/assets/66128387/6450fa42-ab4a-43e2-81d0-5bd4228530f3)
(Slide 41 in [TigerData_PresLayer_CoreFunctionality_v0.6_2023-04-24.pdf](https://drive.google.com/file/d/1814whoDngEuHI3i_u_epd33t0pd2c7fd/view?usp=drive_link))

I had originally envisioned this role coming in post-MVP, but now that we have a better grasp on interoperation between the Presentation Layer and Mediaflux, it's become clear that we need functionality in place for System Administrators up-front.

We already have a few footholds for System Administrators:
- The bare-bones ~/projects page
- The "sysadmin" column of the [TigerData Preliminary Registration List](https://docs.google.com/spreadsheets/d/169lfRTOSe6H66Iu2DK5g-QzqiVsfz5lHFHMaGmwNT7Y)
- #448 and #475 to get some functionality for System Administrators

This issue is about taking the next step and codifying the role of "System Administrator" in software according the [TigerData Role Eligibility Definitions](https://docs.google.com/document/d/1OyOLTd_jMqszRbN_vPhAC_lDB-p4E8czxAGM55Z1FbU), so that we can build out the rest of the features in #553.

### Completion Criteria
- [x] Formally establish the role of "System Administrator"
  - [x] Confirm that all active functionality aligns with the definition in [TigerData Role Eligibility Definitions](https://docs.google.com/document/d/1OyOLTd_jMqszRbN_vPhAC_lDB-p4E8czxAGM55Z1FbU)
  - [x] There are tests proving that the role aligns with the document
- [ ] For now, the only special privilege a System Administrator has in the Presentation Layer is the ability to approve projects
- [x] Use the "sysadmin" column of the [TigerData Preliminary Registration List](https://docs.google.com/spreadsheets/d/169lfRTOSe6H66Iu2DK5g-QzqiVsfz5lHFHMaGmwNT7Y) to assign the System Administrator role to specific persons

**Comment by carolyncole** [comment]
Some of this was done in https://github.com/pulibrary/tiger-data-app/commit/6b661cb9bea035be5a9b5df6f49aba1cb1e0cea0
