### ISSUE TITLE
Refined system administrator dashboard

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/tiger-data-app#572]
### User Story
As a System Administrator, when I log into the Presentation Layer, I need to see an overview of the pending and recently approved projects, so that I can take quick action to make approvals or revisions.

### Context
We have a start with #475. What I want to do next is refine the System Administrator's specialized dashboard to align with my overarching design logic--wherein the most pertinent information for a given role type is displayed in one large panel, front and center. Here's a wireframe:

![image](https://github.com/pulibrary/tiger-data-app/assets/66128387/ba8cba67-3a39-4cb1-bf40-7906fa1ebe1f)

### Completion Criteria
- [x] When a person declared as a System Administrator (see #570) logs in, they get the System Administrator dashboard by default
- [x] The System Administrator dashboard has as its main panel "Project Administration"
- [x] The Project Administration panel has two sections:
  - [x] "Pending Projects" lists the titles of all currently pending projects
    - [x] If there are no projects currently pending, this section stays in place, but states "(none)"
  - [x] "Recently Approved Projects" lists the titles of up to 5 recently approved projects
    - [x] Given in reverse chronological order by the approval provenance timestamp
    - [x] If no projects have been approved, this section stays in place, but states "(none)"
    - [x] If more than 5 projects have been approved, this section contains a "Show More" button, which displays up to 5 more projects in the panel when clicked
- [x] Clicking the title of any project in the Project Administration panel takes the user to the System Administrator version of the Project Details page (see #573)

**Comment by kelynch** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/572?planning-poker) with Zenhub @leefaisonr @carolyncole @hectorcorrea @JaymeeH @jrgriffiniii
