### ISSUE TITLE
Project Approval page for system administrators

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/tiger-data-app#574]
### User Story
As a System Administrator, I need to carefully enter critical information to confirm the approval of a project, so that I can be sure I haven't made any mistakes before I send it through to complete the setup for the Data Sponsor.

### Context
Following up on the early work in #443 and #475, we now need a refined way for System Administrators to approve projects in the Presentation Layer. While the Collection ID from MediaFlux is the key marker of a project's existence, it is not the only bit of information we need to record. Crucially, a System Administrator needs a way to alter the Project Directory and Storage Capacity, as well as to fill out the provenance information. We'll have to streamline this to scale up, but for now, my vision is for assisted manual input: pre-fill everything but the Collection ID and the Event Note, but allow them all to be edited.

![image](https://github.com/pulibrary/tiger-data-app/assets/66128387/fb2d3ca3-0908-4ce5-a39f-2494521d3f7e)

### Completion Criteria
- [x] The page is titled "Project Approval: " with the title of the project appended
- [x] The first section is "Metadata Highlights," which displays the following project metadata fields for the System Administrator's reference:
  - [x] Data Sponsor
  - [x] Affiliated Department(s)
  - [x] Project Directory (requested)
  - [x] Title
  - [x] Project ID
  - [x] Storage Capacity (requested)
  - [x] Submission
- [x] The section is "Project Approval Confirmation Information," which contains the following fields:
  - [x] "Confirm Project Directory"
    - [x] Allows the System Administrator to change the approved directory from what is given by the request form
    - [x] Displays "/tigerdata/" followed by two subfields shown for data entry convenience, segmented by "/"
    - [x] The first subfield is left blank
    - [x] The second subfield is pre-filled with the value entered by the Data Sponsor in the request form
    - [x] The value for the full path is then constructed as "/tigerdata/[subfield1]/[subfield2]"
      - [x] The value as approved gets the attribute "Approved"
  - [x] "Confirm Storage Capacity"
    - [x] Allows the System Administrator to change the approved capacity from what was given by the request form
    - [x] There is one field, which allows a positive integer only, followed by a displayed unit of "GB"
    - [x] The field is pre-filled with the appropriate value from the request form (in GB units)
      - [x] E.g., if the request form entered "100 TB" it is translated to 100000 GB
    - [x] The value is stored as a string constructed from the integer and the unit (e.g., "100000 GB" or "500 GB")
      - [x] The value as approved gets the attribute "Approved"
  - [x] "Collection ID"
    - [x] This field is not pre-filled
    - [x] A value is required
  - [x] "Approver"
    - [x] Prefilled with the NetID of the System Administrator who opened the page
    - [x] Can be edited, but the value must be the NetID of an eligible System Administrator
    - [x] Maps to the provenance field "Submission" :  "ApprovedBy"
  - [x] "Approval Date-Time"
    - [x] Pre-filled with the ISO 8601 timestamp at the moment the page was opened in US Eastern time
    - [x] Can be edited, but must conform to ISO 8601 (with the time zone)
    - [x] Maps to the provenance field "Submission" :  "ApprovalDateTime"
  - [x] "Event Note"
    - [x] Optional and not pre-filled
    - [x] Two subfields:
      - [x] "Type": given by a dropdown menu with the possible values of "Quota", "Tier", and "Other" (no selection by default)
      - [x] "Message": a free-text field (blank by default)
    - [x] Maps to the provenance field "Submission" :  "EventNote", with the following subfields:
      - [x] "NoteBy" filled by the NetID of the System Administrator who opened the page
      - [x] "NoteDateTime" filled by the ISO 8601 timestamp at the moment the "Confirm Approval" button is clicked
      - [x] "EventType" filled by the "Type" selection
      - [x] "Message" filled by the "Message" box entry
- [x] There are two action buttons at the bottom of the page:
  - [x] "Confirm Approval" first performs a validation check (not out to mediaflux, just field values) when clicked
    - [x] If any fields are invalid, they are highlighted on the page with no further action taken
    - [x] If all fields are valid, then the project is approved
      - [x] A provenance event is logged with the approver and approval date-time as entered, as well as the Event Note, if present
      - [x] The provenance "Status" is updated to "Approved"
      - [x] A background job to confirm the connection with MediaFlux is kicked off (see #553)
      - [x] The user is taken to the "Project Approval Received" page (#575)
  - [x] "Cancel" returns the System Administrator to their dashboard without making any changes

**Comment by kelynch** [comment]
This ticket should be evaluated to be broken out into smaller, workable tickets.

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/574?planning-poker) with Zenhub @bess @hectorcorrea @JaymeeH @jrgriffiniii @kelynch @leefaisonr
