### ISSUE TITLE
Project Approval Received page

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/tiger-data-app#575]
### User Story
As a System Administrator, I need to see a confirmation that my project approval went through, so that I can move on to my next task.

### Context
Every major action in the Presentation Layer should have a confirmation message. The message for the System Administrator when approving a project is similar to that for a Data Sponsor when submitting a request for a new project, but with different text.

![image](https://github.com/pulibrary/tiger-data-app/assets/66128387/b35680a8-287d-4332-94fc-d81d1cca3203)

### Completion Criteria
- [x] The page is titled "Project Approval Received"
- [x] The message reads:
> Thank you for your approval.
The Data Sponsor and Data Manager will be notified shortly.
If there are any issues in confirming the Active status of the project, you will receive a message at td-support[at]princeton.edu"
- [x] There is one button at the bottom: "Return to Dashboard"
  - [x] When clicked, the System Administrator should see that the project they just approved is now listed under "Recently Approved Projects"

**Comment by kelynch** [comment]
Current "Approve" button could redirect to this screen before other parts of the process are implemented.

**Comment by kelynch** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/575?planning-poker) with Zenhub @carolyncole @hectorcorrea @JaymeeH @jrgriffiniii @leefaisonr
