### ISSUE TITLE
Displayed URLs for projects

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/tiger-data-app#576]
Can we suppress any internal database record IDs so that users never see them?

Right now, when I'm looking one of my projects (after submitting the request), I see a number in the URL:

![TD_ProjectDetails_URL_2024-03-14](https://github.com/pulibrary/tiger-data-app/assets/66128387/0577d33a-1b73-4d8a-bde1-2f9ab8c7afc9)

Perhaps that is just a feature of the QA/staging instances. But if not, I think a user could confuse that as "the real" project record number, which would be a problem.

Ideally, the only ID that a user ever sees associated with their project is the official Project ID. Moreover, there should be no way to navigate directly to a project except by knowing its official Project ID or Project Directory.

**Comment by bess** [comment]
We discussed this on 20 March 2024. The team + Matt agreed that this can wait. We won't eliminate the internal database id, we'll just mask it in the URL, but down the road.
