### ISSUE TITLE
Move Image from Bess' private repo to quay

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/tiger-data-app#580]
Once we can have private repositories in [Quay move the circle ci mediflux build ](https://github.com/pulibrary/tiger-data-app/blob/main/.circleci/config.yml#L30)from @bess's private repo to where we store our other repos (in quay)

**Comment by bess** [comment]
Closing in favor of a different solution: https://github.com/pulibrary/tiger-data-app/issues/871
