### ISSUE TITLE
Get clarity around who is doing log management, us or OIT

### ISSUE THREAD

**Issue by mccalluc** [pulibrary/tiger-data-app#59]
Even if a view of the logs is not MVP, we should determine soon who will manage the logging. ie, will Mediaflux logs be searchable on datadog? Who will configure that, if so?

**Comment by matthewjchandler** [comment]
Log management on the Mediaflux servers should, in my view, be handled by OIT/Research Computing. If we would like to add or revise a particular log, or make a particular log searchable via our tools of choice, then I recommend we frame that as a request to our colleagues who handle the day-to-day operation of the systems.

**Comment by bess** [comment]
Out of scope for RDSS.
