### ISSUE TITLE
Project directory for project in Mediaflux

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/tiger-data-app#593]
We should read the project directory straight from Mediaflux and display that value for projects that have already been created in Mediaflux.

We currently construct the value with the `api_root_collection_namespace` configuration in `mediaflux.yml` and the value in the database.

The following screenshot shows this issue (this project lives in our sandbox server actually under `/princeton/tigerdata/idp-course` 

![Screenshot 2024-03-21 at 4 15 40 PM](https://github.com/pulibrary/tiger-data-app/assets/568286/c1fbcf32-3776-4b5c-b072-f474cf4d68c0)

Note: Constructing the path as we currently do is OK for projects that have not been created in Mediaflux, since in that case we don't have a full path and we can only guess what it will be based on our configuration.

## Acceptance criteria
- [ ] If a project is not in mediaflux, show the hard coded value (as it does now)
- [ ] If a project IS in mediaflux, get the metadata and show the actual directory value

**Comment by bess** [comment]
This might have been done already. Please check.

**Comment by bess** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/593?planning-poker) with Zenhub @carolyncole @hectorcorrea @JaymeeH @jrgriffiniii
