### ISSUE TITLE
Implement minimal document type

### ISSUE THREAD

**Issue by mccalluc** [pulibrary/tiger-data-app#60]
Required:
- Matt should give us a minimal set of required fields (See below)

## Acceptance criteria
- [ ]  Translate minimal schema into a Mediaflux document type
  - [ ] First do it via the desktop app
  - [ ] Then do it in ruby 
- [ ] We should add code to create this document type to the idempotent seed script: #50
- [ ] We should run the script locally, and confirm that it creates the new document type.

* Note that we will need to be able to set a local schema for development, even if in the short term, OIT is managing the server schema.
* Plan is that the schema document is stored as XML in the tiger-data-app source code

Not in the scope of this issue:
- #58
- Creating a new metadata document using this schema,

**Comment by matthewjchandler** [comment]
I will soon be working with the Metadata Working Group to generate formal documentation and schemas for metadata, but in the meantime, for preliminary testing purposes, let me suggest the following minimal fields for a Project:

- Title
  - Type: string
  - Restrictions: no character limit
  - Cardinality: 1..1
- Short Name
  - Type: string
  - Restrictions: 16-character limit; no spaces or special characters (suitable for a file path)
  - Cardinality: 1..1
- Description
  - Type: string
  - Restrictions: no character limit
  - Cardinality: 0..1
- Data Sponsor
  - Type: user
  - Restrictions: registered NetID
  - Cardinality: 1..1
- Data Manager
  - Type: user
  - Restrictions: registered NetID
  - Cardinality: 1..1
- Data User
  - Type: user
  - Restrictions: registered NetID
  - Cardinality: 0..Infinity
