### ISSUE TITLE
Demonstrate JS/jQuery unit testing

### ISSUE THREAD

**Issue by mccalluc** [pulibrary/tiger-data-app#62]
While our overall test coverage is good, JS is only covered by system tests. It would be good to at least have a handle on how we would write unit tests for JS.

jQuery is a little awkward to test because it's often going to depend on particular HTML structures that come from the ERB, so we would need to recreate these structures in the JS test, and these will need to be kept in sync.

Jest is a popular JS testing framework: [Their docs](https://jestjs.io/docs/tutorial-jquery) provide an example of testing jQuery code.

**Comment by bess** [comment]
This was a useful spike, but after discussion the team decided that system specs are a better choice for this application.
