### ISSUE TITLE
Add a "schema version" field to the mediaflux schema

### ISSUE THREAD

**Issue by bess** [pulibrary/tiger-data-app#628]
Add a "schema version" field to the mediaflux schema, so we can always know what version of the schema a record is using.

- [x] Release this as v0.6.1

Needed for #629

**Comment by matthewjchandler** [comment]
Created a new [version 0.6.1](https://docs.google.com/document/d/1VAO-0Ge18nbiMSDCXIl-sFC9BQgjWdP2VHNll0NAHhI) document. Work in progress...

**Comment by matthewjchandler** [comment]
Completed with the definition of the new [Schema Variant](https://docs.google.com/document/d/1VAO-0Ge18nbiMSDCXIl-sFC9BQgjWdP2VHNll0NAHhI/edit#heading=h.lwiyiel3y5dh) field.
