### ISSUE TITLE
SPIKE - How do we safely write Provenance to Mediaflux

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/tiger-data-app#631]
- [x] Check out the ability to create a stored procedure in Mediaflux (a command)
    - [x] time box 3 days
    - [x] Can we create an example in the sandbox/playground or local Mediflux that is our own command `princeton.project.create` or something like that...
    - [x] Can we trigger that with code

- [x] create an aterm script that system administrators can run if the time box is running out without success

**Comment by JaymeeH** [comment]
A stored procedure will be a TCL script
[More info](https://drive.google.com/drive/u/1/folders/1UqQlsx91hVlc2YFIVmnBHLfO8iiMIP6U): Tigerdata / Mediaflux Recordings / Developer 101 / Session 2
