### ISSUE TITLE
Refactor the #approve_project method

### ISSUE THREAD

**Issue by bess** [pulibrary/tiger-data-app#639]
Look in the projects controller, in the update method.

![Screenshot 2024-04-12 at 3 30 23 PM](https://github.com/pulibrary/tiger-data-app/assets/65608/8d7060a0-f901-4e93-9286-0ce9c8cad413)

## Acceptance criteria
- [x] Calling the #approve_project method on a project sets the status to `Project::APPROVED_STATUS`

**Comment by JaymeeH** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/639?planning-poker) with Zenhub @bess @jrgriffiniii @kelynch @hectorcorrea @carolyncole @leefaisonr
