### ISSUE TITLE
Set the project to active

### ISSUE THREAD

**Issue by bess** [pulibrary/tiger-data-app#640]
Per ADR #7, we have a status of "approved", which means a sysadmin has approved it, and we now have a status of "active", which means it has a valid `mediaflux_id`

## Acceptance criteria
- [x] There is a method called #activate_project next to the #approve_project method
- [x] it checks whether the project has a mediaflux_id
- [x] it queries mediaflux for that id and verifies that the DOI of the project in rails matches the DOI in mediaflux
- [x] If so: 
  - [x] it sets the status to `Project::ACTIVE_STATUS`
  - [x] it records a `ACTIVE_EVENT_TYPE` provenance event for this project

**Comment by JaymeeH** [comment]
@bess If we query mediaflux, and the DOI's do not match or that particular mediaflux id does not exist in mediaflux, when/how often should we run the check against mediaflux? Do you think we should implement this a service class that runs a background job automatically after a certain interval for all pending projects?

**Comment by bess** [comment]
@JaymeeH I think this ticket describes the background job we need: https://github.com/pulibrary/tiger-data-app/issues/630
And yeah, having a service class that runs the background job after a certain interval for all pending projects makes sense.
