### ISSUE TITLE
Custom error page for application and Rails errors

### ISSUE THREAD

**Issue by kelynch** [pulibrary/tiger-data-app#649]
When the load balancer would normally serve the "something went wrong!" page, display custom error text that tells users where to open a ticket for support.

This will be the TigerData RT queue.  Let's ensure that everyone in RDSS is on this, so that notifications can be received by RC, PRDS, and RDSS for the time being.  

## Acceptance Criteria

- [ ] Ensure that all of RDSS is on the TigerData RT queue
- [ ] Get custom error page text from @matthewjchandler (see below)
- [ ] Design custom error page
- [ ] Implement custom error page
- [ ] Ensure that the load balancer shows a custom error page for tigerdata
- [ ] Ensure that any random exception displays the custom error page as well via a application controller rescue

**Comment by matthewjchandler** [comment]
Here's the text I recommend to start with:

Heading: "Something went wrong"
Message: "Please bear with us as the TigerData portal still has multiple areas under construction. We track errors automatically, but please feel free to reach out for support any time."
Contact line: "[Contact TigerData Support](mailto:td-support@princeton.edu)"
[insert TigerData logo bottom-center]

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/649?planning-poker) with Zenhub @JaymeeH @jrgriffiniii @leefaisonr @kelynch

**Comment by carolyncole** [comment]
https://github.com/pulibrary/princeton_ansible/pull/5088

**Comment by carolyncole** [comment]
This is blocked by moving the tigerdata machines to the dev load balancer.  @kayiwa and I will pair on this

**Comment by carolyncole** [comment]
will be fixed by https://github.com/pulibrary/princeton_ansible/pull/5088
