### ISSUE TITLE
When a project is missing metadata, mediaflux silently fails to create it

### ISSUE THREAD

**Issue by bess** [pulibrary/tiger-data-app#650]
### Expected behavior
I expect that if I make a project in mediaflux, and that project fails to be created because it is missing required metadata, that there would be a meaningful error telling me what information is missing so I can fix the issue. 

### Actual behavior
Instead, it just silently fails. We can tell the mediaflux asset wasn't created, but we can't easily tell why.

### Steps to replicate
```
(byebug) project = FactoryBot.create(:project)
#<Project id: 1378, mediaflux_id: nil, metadata_json: {"data_sponsor"=>"danuta_carroll", "data_manager"=>"nathanaeljustin", "data_user_read_only"=>[], "data_user_read_write"=>[], "departments"=>["RDSS", "PRDS"], "directory"=>"big-data", "title"=>"The Men from Outer Space", "description"=>"a random description", "created_on"=>"2024-04-19T08:10:56-04:00", "created_by"=>"edison", "updated_on"=>"2024-04-19T08:10:56-04:00", "updated_by"=>"desmond", "project_id"=>nil, "status"=>"pending", "storage_capacity_requested"=>"500 GB", "storage_performance_expectations_requested"=>"standard", "project_purpose"=>"research"}, created_at: "2024-04-19 12:10:56.932476000 +0000", updated_at: "2024-04-19 12:10:56.932476000 +0000">
(byebug) project.mediaflux_id = ProjectMediaflux.create!(project:, session_id: )
"" <-- The mediaflux project wasn't created, but it isn't clear why, we just get a blank id back
(byebug) project.mediaflux_id
nil 
```

Whereas, if we create the `project` object with the required metadata: 
```
(byebug) project = FactoryBot.create(:project, project_id: "doi:123:456", directory: "something")
#<Project id: 1380, mediaflux_id: nil, metadata_json: {"data_sponsor"=>"brian", "data_manager"=>"fritz_erdman", "data_user_read_only"=>[], "data_user_read_write"=>[], "departments"=>["RDSS", "PRDS"], "directory"=>"something", "title"=>"Death Brain", "description"=>"a random description", "created_on"=>"2024-04-19T08:17:46-04:00", "created_by"=>"enoch", "updated_on"=>"2024-04-19T08:17:46-04:00", "updated_by"=>"efren_jerde", "project_id"=>"doi:123:456", "status"=>"pending", "storage_capacity_requested"=>"500 GB", "storage_performance_expectations_requested"=>"standard", "project_purpose"=>"research"}, created_at: "2024-04-19 12:17:46.364057000 +0000", updated_at: "2024-04-19 12:17:46.364057000 +0000">
(byebug) project.mediaflux_id = ProjectMediaflux.create!(project:, session_id: )
"1319" <-- Now mediaflux made an asset and gave us the ID
```

### Impact of this bug
We spend more time than we should figuring out why something wasn't created in mediaflux. As our schema evolves, and as we face the challenge of keeping the schema definition in rails in sync with the schema definition in mediaflux, it's going to become ever more important to detect metadata issues early and clearly. 

### Implementation notes, if any
I'd like to see a custom exception class raised for metadata issues. This would allow us to see them in Honeybadger and know how often they're happening. All exceptions that are raised should include the current expected metadata schema version number, as well as what metadata is missing.

**Comment by JaymeeH** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/650?planning-poker) with Zenhub @bess @carolyncole @hectorcorrea @jrgriffiniii @kelynch @leefaisonr
