### ISSUE TITLE
Pre-fill approval form

### ISSUE THREAD

**Issue by bess** [pulibrary/tiger-data-app#694]
<img width="953" alt="Screenshot 2024-05-08 at 10 19 55 AM" src="https://github.com/pulibrary/tiger-data-app/assets/65608/f20eded4-bd8f-49da-9cf6-45d3fec5ef1e">

### Acceptance Criteria:

- [ ] If the value in the form remains the same the user does not need to enter information for Project Directory, Capacity, and Approval Date Time

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/694?planning-poker) with Zenhub @bess @hectorcorrea @JaymeeH @leefaisonr
