### ISSUE TITLE
Update Project create_script to reflect new Tigerdata schema

### ISSUE THREAD

**Issue by JaymeeH** [pulibrary/tiger-data-app#742]
Right now, the `Project:create_script` rake task is missing several key metadata values, and will cause multiple errors when attempting to execute in Aterm. Update the script to reflect the newer `0.6.1` Tigerdata schema

Acceptance criteria
- [ ] utilized the code in [Hector's PR](https://github.com/pulibrary/tiger-data-app/pull/721/files#diff-1d8eacc354c577f4516e6b4f6bbef6dd7b1a133ae9ad196e7c34c24083666737) for reference
- [ ] in [lib/tasks/projects.rake](https://github.com/pulibrary/tiger-data-app/blob/main/lib/tasks/projects.rake) —  update the asset.create command in the script
     - [ ] Remove `Code` => Project ID
     - [ ] Add `ProjectDirectory`
     - [ ] Add `Submission`
     - [ ] Refactor `StoragePerformance` to just `Performance`
     - [ ] Add `SchemaVersion`

**Comment by hectorcorrea** [comment]
I started making these changes in this PR https://github.com/pulibrary/tiger-data-app/pull/721 but then got side tracked and added a bunch of other unrelated changes to the PR. But it can serve as a guideline.

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/742?planning-poker) with Zenhub @hectorcorrea @JaymeeH @jrgriffiniii @leefaisonr
