### ISSUE TITLE
We are currently completely deleting the User Job instead of just removing the download link

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/tiger-data-app#752]
When we discussed https://github.com/pulibrary/tiger-data-app/issues/542 with @matthewjchandler They asked that we only remove the link, but not the entire activity.

## Completion criteria:

- [x] Rename `DeleteUserJob` ([here](https://github.com/pulibrary/tiger-data-app/blob/main/app/jobs/delete_user_job.rb)) to `CleanupFileInventoryRequestJob`
- [x] Update the code in https://github.com/pulibrary/tiger-data-app/pull/750 to mark the job as stale instead of [deleting it](https://github.com/pulibrary/tiger-data-app/pull/750/files#diff-8431dffc1b41c7bc1b402781c524aa53d800bf8f8631a4912f36bd02dc032000R8)
- [x] If a `FileInventoryRequest` is stale, do not display the download link in the Recent Activity section 
- [x] It deletes any files from the filesystem listed in the `FileInventoryRequest#request_details`
- [x] Remove the cron scheduling for the rake task `exports::delete_old` from config/schedule.rb, but leave the rake task in place in case we want to run it manually

**Comment by carolyncole** [comment]
@matthewjchandler How strongly do you feel about having the record of the request still exist.  The code that was currently implemented by @JaymeeH completely deletes the UserJob.  We could just leave that in place and close this ticket.

**Comment by matthewjchandler** [comment]
I feel strongly that the "recent activity" pane should retain useful information for a reasonable period of time, and I feel strongly that it should be possible to retrieve a log of all activity on a project for even longer than the activities show in the "recent activity" pane, but I'm not certain that's what you're asking. I think it makes sense to delete downloaded files after a week--and a hard delete (not just a link removal) works for me. I don't think a week is always long enough to remove items listed under the "recent activity" pane, if that is indeed implied.

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/752?planning-poker) with Zenhub @hectorcorrea @JaymeeH @leefaisonr @jrgriffiniii

**Comment by JaymeeH** [comment]
This is addressed in the [Tigerdata Refactor](https://github.com/pulibrary/tiger-data-app/issues/773)
