### ISSUE TITLE
Add language to dashboard about file list download

### ISSUE THREAD

**Issue by kelynch** [pulibrary/tiger-data-app#762]
Add language to the "file list is being generated in the background" message to indicate that the user A) can safely close the tab and B) that the report will be available in their dashboard when it is ready.

Add to the message box highlighted in this screenshot:
![Screenshot 2024-06-10 at 1 55 10 PM](https://github.com/pulibrary/tiger-data-app/assets/7795797/d7873247-13d1-4f67-8018-d74a7e2f3061)

## Acceptance criteria
- [x] [Wording](https://github.com/pulibrary/tiger-data-app/issues/762#issuecomment-2158985669) to convey this information has been added to this ticket.
- [ ] This wording has been added to the correct status message in the application [code here](https://github.com/pulibrary/tiger-data-app/blob/7528273df6a5b30ea152877379353f8a47f247e8/app/controllers/projects_controller.rb#L189).

**Comment by kelynch** [comment]
Proposed language for the message: 

> File list for "Read only test 6-6-2024" is being generated in the background.  A link to the downloadable file list will be available in the "Recent Activity" section of your dashboard when it is available.  You may safely navigate away from this page or close this tab.

@matthewjchandler how does this sound?  Please feel free to make changes to the language.

**Comment by matthewjchandler** [comment]
Yes, that looks good to me!
