### ISSUE TITLE
Create a class named ProjectAccumulators that knows to create three accumulators for a project

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/tiger-data-app#768]
### What maintenance needs to be done?
Create a class in either the models directory or the models/mediaflux directory based on the implementors feeling.  The code for this ticket already [exists here]( https://github.com/pulibrary/tiger-data-app/blob/main/app/models/project_mediaflux.rb#L63-L78)

```
my_project = Project.new; ProjectAccumulator.new(my_project).create!
ProjectAccumulator should be idempotent - we should be able to run this more than once and it should just do the right thing
ProjectAccumulator.new(my_project).validate => check that existing accumulators match our expectation
```

### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

### Acceptance criteria
 - [x] Pull the code from ProjectMediaflux create_accumulators into a class
 - [x] the class will have two methods one for create!, which does nothing if nothing is needed and validate, which determines if the project has accumulators correctly applied.
 - [x] Write a test that connects to mediaflux and creates the accumulators on a project
 - [x] Write a test that connects to mediaflux and validates the accumulators on a project

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/768?planning-poker) with Zenhub @hectorcorrea @JaymeeH @jrgriffiniii @kelynch @leefaisonr

**Comment by JaymeeH** [comment]
@carolyncole what does `which does nothing if nothing is needed ` mean in this context? we want ProjectAccumulators.create! to actually create all three necessary accumulators right?

**Comment by carolyncole** [comment]
@JaymeeH the `create!` method (`one for create!, which does nothing if nothing is needed`)

**Comment by JaymeeH** [comment]
Ok — I understand

**Comment by JaymeeH** [comment]
@carolyncole right now, so far we have only ever created accumulators for `collection.asset.count` and `content.all.size`, do you know what the third accumulator is supposed to be used for?

**Comment by carolyncole** [comment]
This has the information near the end on what accumulators Chuck creates https://princetonrc.slack.com/files/U05T4KHDH4P/F077BRM891P/project_creation_script_for_pena-ffcws.txt
