### ISSUE TITLE
Create the quota during project creation

### ISSUE THREAD

**Issue by bess** [pulibrary/tiger-data-app#789]
## Acceptance criteria
- [x] Add the quota element to the project create so we don't have to do a quota create request
- [x] Remove the `QuotaCreateCollectionRequest` class

Information on how to create the quota as we create the project: https://pulibrary.slack.com/archives/C05CCH34YBY/p1717704970910909

**Comment by bess** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/789?planning-poker) with Zenhub @carolyncole @hectorcorrea @JaymeeH @jrgriffiniii @leefaisonr

**Comment by carolyncole** [comment]
Chuck is utilizing this instead of a separate call
![Screenshot 2024-07-08 at 10 27 12 AM](https://github.com/pulibrary/tiger-data-app/assets/1599081/fc950ab1-c917-4fbd-b984-9ebfc77b19be)

**Comment by carolyncole** [comment]
Based on the docs it should live at the same level in the XML as meta https://github.com/pulibrary/tiger-data-app/blob/main/app/models/mediaflux/http/project_create_request.rb#L41

**Comment by leefaisonr** [comment]
Closed by #807
