### ISSUE TITLE
Deploy new tiger-data application

### ISSUE THREAD

**Issue by mccalluc** [pulibrary/tiger-data-app#8]
Follow the patterns in https://github.com/pulibrary/princeton_ansible.

Review https://github.com/pulibrary/pdc_describe/issues/4 and see if it's a good model for this issue.

## Acceptance Criteria
- [ ] tiger-data-app (Rails application) can be spun up and run
- [ ] Integrate tiger-data-app into CI
- [ ] You can access the application at the staging and prod URLs below

**Comment by kelynch** [comment]
tigerdata-staging and tigerdata-prod should be the naming conventions.
