### ISSUE TITLE
Rake task mediaflux:destructive_cleanup

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/tiger-data-app#813]
Rake task `mediaflux:destructive_cleanup` is cleaning `/td-demo-001/tigerdataNS` but it should be cleaning `/td-demo-001`

- [x] Investigate if this is still true
- [ ] If it is still happening change the rake task to destruct the correct location

**Comment by carolyncole** [comment]
This is still an issue and the destructive clean up does not clean up the collections, only the namespaces.
