### ISSUE TITLE
[Tiger Data/staging] NameError: uninitialized constant DeleteUserJob

### ISSUE THREAD

**Issue by bess** [pulibrary/tiger-data-app#820]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/113559/faults/108907222)

## Steps
We think this was because there were jobs in Sidekiq that were referencing a class that has been deleted. 

[ ] Clear the queue on Sidekiq
[ ] If it happens again then look into it but it should not.

**Comment by hectorcorrea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/820?planning-poker) with Zenhub @carolyncole @JaymeeH @jrgriffiniii @kelynch @leefaisonr

**Comment by carolyncole** [comment]
Has not happened since I cleared the queue
