### ISSUE TITLE
Capistrano deployments fail for tigerdata-staging1 (but not tigerdata-staging2)

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/tiger-data-app#829]
This is related to integration with the Datadog monitoring agent, as the errors are logged within Ansible Tower at the following:
https://ansible-tower.princeton.edu/#/jobs/playbook/2908/output

By troubleshooting this using `bundle exec cap staging deploy`, it was discovered that the `ddtrace` Gem could not connect to the Datadog agent.

Acceptance Criteria:
- [ ] Ensure that Capistrano deployments are successful for `tigerdata-staging1`
- [ ] Ensure that Capistrano deployments remain successful for `tigerdata-staging2`, `qa`, and `prod` host servers

**Comment by carolyncole** [comment]
I think this may have been an issue that was created when we were moving tigerdata-staging2 to the new network.  I believe the branch needs to be rebased with main to get the new server names.

**Comment by carolyncole** [comment]
I believe this is not an issue.  Main deploys just fine.  I think the deployment to staging occurred during the transition of staging from tigerdata-staging.princeton.edu to tigerdata-staging.**lib**.princeton.edu
