### ISSUE TITLE
Add an http header to the requests we send to mediaflux

### ISSUE THREAD

**Issue by bess** [pulibrary/tiger-data-app#834]
Add an http header to the requests we send to mediaflux which indicates whether the user has authenticated via CAS.

## Acceptance criteria
- [ ] If a user has authenticated via CAS, there is a header in the http requests sent to mediaflux
  - [ ] the header includes the netid `TIGERDATA_NETID` - the user netid that is logged in
  - [ ] the header includes domain:princeton `TIGERDATA_DOMAIN` - Hardcoded to `princeton`
  - [ ] the header includes the CAS timeout data `TIGERDATA_TIMEOUT` - Follow the format from CAS
- [ ] No call sto mediaflux should be made if we are not logged in, but if this happens then
     - [ ] If a user has not authenticated via CAS that header does not exist or is empty
     - [ ] If a user's CAS session has expired, that header does not exist or is empty

See #836 for the Mediaflux component of this ticket.

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/834?planning-poker) with Zenhub @hectorcorrea @JaymeeH @jrgriffiniii @kelynch @leefaisonr @bess
