### ISSUE TITLE
Version number in footer of the application 

### ISSUE THREAD

**Issue by bess** [pulibrary/tiger-data-app#86]
Put the version number in the footer of the application. Follow the example in PDC Describe (https://github.com/pulibrary/pdc_describe/search?q=VersionFooter). 

Copy and paste the classes from PDCDescribe into Tigerdata

**Comment by kelynch** [comment]
Example: https://github.com/pulibrary/pdc_describe/search?q=VersionFooter

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/86?planning-poker) with Zenhub @bess @jrgriffiniii
