### ISSUE TITLE
Set up lib-mediaflux service account

### ISSUE THREAD

**Issue by bess** [pulibrary/tiger-data-app#867]
This is the service account that will be used on the mediaflux boxes to bind to active directory. Details are current in an email from Steph Ayers.

31 July update: I tried to follow the instructions in the email, but they do not work, as they require an email authentication to be sent to Steph Ayers. I've asked Steph whether she can set up a password for this account.

### Acceptance criteria
- [x] Create a password
- [x] Store it in lastpass
- [x] Let the team know

**Comment by bess** [comment]
Steph has now added me & Kate as contacts on this email, but as of 8am Thursday Aug 1 I still cannot set a password; it only accepts Steph Ayers as the email address to which to send confirmations.

**Comment by bess** [comment]
Tried again Thursday evening and still couldn't add a password. Steph Ayers says she's going to do it for us.

**Comment by kelynch** [comment]
Password set and stored in LastPass.  Closing.
