### ISSUE TITLE
Add desktop servlet to mediaflux

### ISSUE THREAD

**Issue by bess** [pulibrary/tiger-data-app#869]
Our ansible build needs to also install the mediaflux desktop. 

In aterm: `package.install :url https://www.arcitecta.com/software/adesktop/1.2.020/adesktop_1.2.020.zip`

Check that it works: 
```
> package.describe :package "Mediaflux Desktop"
> http.processor.describe :url desktop
```

Acceptance criteria:

- [x] Investigate how to allow ansible to run an aterm command from the command line
- [x] Utilize the above to add the aterm command into the ansible build

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/869?planning-poker) with Zenhub @JaymeeH @jrgriffiniii @leefaisonr @hectorcorrea @kelynch

**Comment by hectorcorrea** [comment]
Notice that you can execute a Aterm command directly from the command line. Below is an example on how to run the `server.version` command:

```
java -Dmf.host=0.0.0.0 -Dmf.port=8888 -Dmf.transport=http -Dmf.domain=system -Dmf.user=manager -Dmf.password=change_me -jar aterm.jar --app exec server.version
```


There is also a way to pass the credentials via a config file specified through the `-Dmf.config` parameter. Run `java -jar aterm.jar --help` to get the syntax for this config file.

**Comment by hectorcorrea** [comment]
The following command will install the Mediaflux desktop directly from the Mac/Linux terminal:

```
$ java -Dmf.host=0.0.0.0 -Dmf.port=8888 -Dmf.transport=http -Dmf.domain=system -Dmf.user=manager -Dmf.password=change_me -jar aterm.jar --app exec package.install :url https://www.arcitecta.com/software/adesktop/1.2.020/adesktop_1.2.020.zip

:package -name "Mediaflux Desktop" -version "1.2.020" "Mediaflux Desktop"
```

**Comment by hectorcorrea** [comment]
@JaymeeH if `aterm.jar` is not on the machine you should be able to download it from the running Mediaflux server. See https://github.com/pulibrary/tiger-data-app/blob/main/docs/local_development.md#accessing-the-thick-client-aterm
