### ISSUE TITLE
Document release and deploy process

### ISSUE THREAD

**Issue by bess** [pulibrary/tiger-data-app#87]
The README should contain instructions for how to release and deploy this app, even if it's just a pointer to the RDSS handbook standard practice. 

Completion Criteria:
- [x] Instructions is for Capistrano deployment for our rails application should either be in the Readme.md or linked to in the Readme.md

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/87?planning-poker) with Zenhub @bess @hectorcorrea @jrgriffiniii

**Comment by jrgriffiniii** [comment]
This was closed by #164
