### ISSUE TITLE
CI should test against our ansible build

### ISSUE THREAD

**Issue by bess** [pulibrary/tiger-data-app#871]
Instead of testing our CI process against the docker container we use for development, we should use mflux-ci.lib.princeton.edu, which will be configured via our ansible playbook.

**Comment by JaymeeH** [comment]
1. Tested that our test suite can make requests to `mflux-ci.lib.princeton.edu` or` mflux-staging.lib.princeton.edu`
2. Test that CI can make requests to `mflux-ci.lib.princeton.edu`
3. Once CAS Auth is up & running, see if we can move away from the docker build of mediaflux and test/develop against a test server i.e `mflux-test.lib.princeton.edu`

**Comment by JaymeeH** [comment]
`connect_to_mediaflux` will reset the api_host to `0.0.0.0` before every test. After commenting that out — we are able to connect and make real requests to `mflux-ci.lib.princeton.edu`! CI as of now is still trying to run mediaflux against an mediaflux instance — which can be changed but the mac address of the mflux-ci build is needed to do so
