### ISSUE TITLE
Mediaflux indicator / websockets not working in qa

### ISSUE THREAD

**Issue by bess** [pulibrary/tiger-data-app#876]
![Screenshot 2024-08-02 at 8 18 55 AM 1](https://github.com/user-attachments/assets/74cc13eb-0274-43a1-839f-2fac5b1aee7c)

**Comment by hectorcorrea** [comment]
We've removed the status indicator from the header and tracking via the health page instead (https://github.com/pulibrary/tiger-data-app/issues/883)
