### ISSUE TITLE
Install DataDog

### ISSUE THREAD

**Issue by bess** [pulibrary/tiger-data-app#88]
We are going to want APM so we can keep an eye on performance from the start. 

- [x] Double check the datadog configuration in princeton-ansible to make sure it specifies APM information
- [x] Create APM dashboards in datadog web site or figure out an existing dashboard that can be linked
- [x] Document where to find these APM dashboards in the README or a docs folder

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/88?planning-poker) with Zenhub @bess @hectorcorrea @jrgriffiniii

**Comment by jrgriffiniii** [comment]
Following the testing of , I can confirm that `tigerdata-prod1` is effectively communicating with DataDog:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdW9aIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f15cd5e110b8704f5686de3ac3e3eb972b8301f0/image.png)

**Comment by jrgriffiniii** [comment]
I have configured a preliminary dashboard at the following in order to provide visualizations of server metrics: https://app.datadoghq.com/dashboard/bpm-nfh-tbk/tigerdata-dashboard

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdHdhIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1f5a091ef9703ecfbb9dfbd96f303540d488678c/image.png)

**Comment by jrgriffiniii** [comment]
I am still struggling with regards to ensuring that the `Service` on DataDog is registered through the API, and I am trying to advance this.

**Comment by kelynch** [comment]
Can this be closed?

**Comment by jrgriffiniii** [comment]
Monitors have been configured and tested for CPU usage, memory usage, and disk space for the `tigerdata-prod1` and `tigerdata-prod2` server hosts on Datadog:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBczlVIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8245c2b842e8b3303825faec7c6bc44094ec6a34/image.png)
