### ISSUE TITLE
Deploy application with Ansible tower

### ISSUE THREAD

**Issue by bess** [pulibrary/tiger-data-app#90]
We are unable to use pulbot to deploy tiger-data-app because it is on jammy jellyfish Ubuntu and something is broken for deployment on all jammy jellyfix boxes. (See https://gist.github.com/pulbot/778199fe73f43b8a03ddca9cbc59550e for example error.)

Troubleshooting document: https://docs.google.com/document/d/1nqza7ThK5YrWbqaSdDZGOpk8fMzkeGkzHj0vzWs4g5E/edit

Since we want to retire our old pulbot deployment process and replace it with Ansible tower deployment, this seems like an opportune time to move, rather than put more effort into fixing an old system that we want to sunset anyway.

## Acceptance criteria
- [x] Be able to deploy tiger-data-app via ansible-tower
- [x] Document the process

**Comment by acozine** [comment]
Related to https://github.com/pulibrary/princeton_ansible/pull/3703
