### ISSUE TITLE
What credentials should the tiger-data-app server use to connect to mediaflux staging? 

### ISSUE THREAD

**Issue by bess** [pulibrary/tiger-data-app#93]
We all have individual logins, but what should the application use? 

This could be a short term solution (e.g., a temporary login and password) but we do need SOMETHING in place in order to develop a prototype.

**Comment by kelynch** [comment]
I think we should use CAS which is already in place.  We could set up a sponsored account or service account long-term, but could do prototyping with one of the existing individual logins as application config settings/env vars to allow us to get started.

**Comment by kelynch** [comment]
This is where we can request a service account down the road - https://princeton.service-now.com/service?id=service_offering&sys_id=3b74d6fa4f2e5200b28af7e18110c7a8.

**Comment by mccalluc** [comment]
Carolyn is going to follow up to get a service account.

**Comment by carolyncole** [comment]
Carolyn wrote a ticket @mccalluc https://github.com/pulibrary/rdss-catchall/issues/87. Anyone can work it...

**Comment by carolyncole** [comment]
We have a service account
