### ISSUE TITLE
Demonstrate connectivity to MediaFlux in the UI

### ISSUE THREAD

**Issue by kelynch** [pulibrary/tiger-data-app#98]
List the files in a namespace from MediaFlux into the UI.  The namespace can be hard-coded at this time, for the purposes of demonstrating our ability for the Rails application to communicate with the MediaFlux server.

After you login you will see a list of items from a path in mediaflux

- [x] A logged in user: On the home page a list of collection assets is shown from in the base path
- [x] A non logged in user should see nothing
- [x] No test should be created

Utilize the code in [Experiments](https://github.com/pulibrary/tiger-data-experiments/blob/main/simple-nokogiri/list_collections.rb#L8-L28)

**Comment by kelynch** [comment]
Ideally we'd love to demo this during the stakeholder retreat (March 13).

**Comment by jrgriffiniii** [comment]
Specifying the `namespace` arguments when listing the collections seems to be required. While I have been attempting to adjust the `size` argument, this still triggers server response timeout errors.

**Comment by jrgriffiniii** [comment]
I apologize, I have progressed with https://github.com/pulibrary/tiger-data-app/compare/jrgriffiniii-mflux-collection-query?expand=1 thus far. I am sorry for the absence of test coverage, I can look to address this following a meeting this afternoon.
